APPS-3279 Complex end-to-end scenario for Payone PBC
spryker/robotframework-suite-tests pull request #123
Opened 2022-04-11 07:29 UTC by miroshnikov-spryker

## PR Description

Ticket: https://spryker.atlassian.net/browse/APPS-3279

2022-04-12 10:38 UTC, stereomon requested changes
How long does test execution take?
Can I see it in action?
How to prevent people from adding step definitions that already exist but are slightly different? E.g. `wait for order item to be in state` vs `wait for order item in state`?
Can we run on travis as well as locally?

2022-04-12 10:38 UTC, stereomon commented on resources/steps/order_history_steps.robot
> +Yves: 'Order History' page contains the following order with a status:
```suggestion
Yves: 'Order History' page contains an order with a status:
```

2022-04-12 10:38 UTC, stereomon commented on resources/steps/payone_steps.robot
> +Payone: submit credit card form with the following data:
I would remove `following` from all cases. It could be always simplified here `submit credit card with data`

2022-04-12 10:38 UTC, stereomon commented on resources/steps/payone_steps.robot
> +Payone: close Beeceptor relay
Can't this be closed automatically? WIll it be a problem when people forget to close?

2022-04-12 10:38 UTC, stereomon commented on resources/steps/zed_payment_methods_steps.robot
> +Zed: activate payment method:
Why do activate and deactivate so differently? Couldn't you use `activate/deactivate payment method` with the same?

2022-04-12 10:38 UTC, stereomon commented on tests/api/suite_nonsplit/glue/category_nodes.robot
> +
Check for too many empty lines in all files.

2022-04-12 10:38 UTC, stereomon commented on tests/api/suite_nonsplit/glue/category_nodes.robot
> +My_first_test
I guess this is just a test??

2022-04-12 10:38 UTC, stereomon commented on tests/api/suite_nonsplit/glue/category_nodes.robot
> +Request_category_node_in_different_languages
When we use Robot only to have Gherkin Spec like BDD tests why not use https://codeception.com/docs/07-BDD?

Codeception is known by all of us and adding Step definitions can be done in PHP we also all know.

2022-04-12 10:38 UTC, stereomon commented on tests/e2e/aop/usercentrics_e2e_connect_pbc.robot
> +Usercentrics_connect_application_eves
What is `eves`?

2022-04-12 10:38 UTC, stereomon commented on tests/e2e/aop/usercentrics_e2e_connect_pbc.robot
> +    #открыл стейдж
Ganz genau das was jeder versteht :D 

Please remove.

2022-04-12 10:39 UTC, stereomon commented
IMO we should evaluate https://codeception.com/docs/07-BDD as it would allow us to build what we need in PHP in the same way.

2022-04-12 14:00 UTC, AntonShopin commented on resources/pages/apps/apps_payone_cc_payment_page.robot
> +${apps_payone_payment_cc_card_type}       xpath=//select[@id='cardtype']
when you have the possibility to use an ID, please avoid using the XPath. In this case, locators with IDs should be changed to `id=cardtype`

2022-04-12 14:00 UTC, AntonShopin commented on resources/pages/zed/zed_aop_pbc_details_page.robot
> +${pbc_configuration_form_save_button}    xpath=//app-configuration//spy-header//spy-button//button[text()='Save']
what was wrong with the previous locator? Using text locators is the last case to go, always try to use ids, names, classes, data-qa and only as the last case -> text

2022-04-12 14:00 UTC, AntonShopin commented on resources/steps/checkout_steps.robot
> +    ...    Click    //form[@name='paymentForm']//h5[contains(text(), '${paymentProvider}')]/following::label//span[contains(text(), '${paymentMethod}')]
- please try to find a better locator instead of using 'h5' in the path. 
- also, you are adding a new logic for b2b env, why not to check and add it for b2c and suite?

2022-04-12 14:00 UTC, AntonShopin commented on resources/steps/orders_management_steps.robot
> +Yves: get the last placed order ID
what is the difference between this and already existing `Yves: get the last placed order ID by current customer` ?

2022-04-12 14:00 UTC, AntonShopin commented on tests/e2e/aop/payone_pbc.robot
> +    ${lastPlacedOrder}=    Yves: get the last placed order ID
Inside `Yves: get the last placed order ID` you already set suite variable and return it, I don't see a need here to declare a variable

2022-04-12 14:00 UTC, AntonShopin commented on tests/e2e/aop/usercentrics_e2e_connect_pbc.robot
> +Usercentrics_connect_application_zed
I think it's your first test and you'll refactor it in BDD, right?

2022-04-12 16:51 UTC, miroshnikov-spryker commented on resources/common/common.robot
>      [Documentation]    will reload page until element is shown/disappear. Secon argument is the expected condition (true/false) for the element.
Default implementation covers "JS adds/removes element" case. This wrapper is needed in case of async background processes when changes are visible only after reloading and we don't know exactly when. There are currently no usages for disappearance checking, but a can think of couple cases, for example: we have disconnected BazaarVoice PBC and checking that bazaarvoice js script should disappear from page.

2022-04-12 17:03 UTC, miroshnikov-spryker commented on resources/common/common.robot
> +#Migration to the Browser Library
I have just cleaned extra white spaces.
But this comment probably refers to switching from using Selenium to Browser as a WebDriver and methods that declared next are wrappers for Browser library API making it look like Selenium API and they were created for migration purpose, I suppose.

2022-04-12 17:12 UTC, miroshnikov-spryker commented on resources/common/common.robot
>      FOR    ${key}    ${value}    IN    &{arguments}
This is a quirk of Robot Framework syntax. It allows white spaces in arguments to make scenarios look more like ordinary text but requires [at least two spaces between tokens](https://robocorp.com/docs/languages-and-frameworks/robot-framework/syntax#space-separated-syntax)

2022-04-12 17:25 UTC, miroshnikov-spryker commented on resources/common/common_aop.robot
> +Library                   Browser    jsextension=${CURDIR}/../libraries/playwright/module.js
I tried to mimic the style used in other files. There are not conventions [I'm aware of](https://spryker.atlassian.net/wiki/spaces/PS/pages/3146187043/Robot+Framework+-+Naming+Convention) regulating this thing.

2022-04-12 17:28 UTC, miroshnikov-spryker commented on resources/common/common_zed.robot
>  Zed: click button in Header:
There are no conventions regulating this. The only doc I found regarding naming conventions is [here](https://spryker.atlassian.net/wiki/spaces/PS/pages/3146187043/Robot+Framework+-+Naming+Convention)

2022-04-12 17:29 UTC, miroshnikov-spryker commented on resources/libraries/playwright/module.js
> +async function injectRequestApiIntoPage(page) {
This repo doesn't contain .editorconfig at all. Is there one agreed .editorconfig that should be applied across all spryker repos?

2022-04-12 17:34 UTC, miroshnikov-spryker commented on resources/steps/checkout_steps.robot
>  Yves: select the following existing address on the checkout as 'shipping' address and go next:
This method is used 36 times. I don't think this suggestion should be applied in this particular PR. Should I create separate task for refactoring?

2022-04-12 17:37 UTC, miroshnikov-spryker commented on resources/steps/checkout_steps.robot
>  Yves: fill in the following new billing address:
4 usages + [this](https://github.com/spryker/robotframework-suite-tests/pull/123#discussion_r848111040)

2022-04-12 17:47 UTC, miroshnikov-spryker commented on resources/steps/checkout_steps.robot
>  Yves: select the following shipping method for the shipment:
Probably because of different use-cases. I can see this method is used consecutively in scenarios with multiple shippings for selecting different methods for each shipping.
I totally agree that this methods are building blocks for creating simple and clear tests-cases in future and we should create them with more thoughtfulness and responsibility, but I think this is a subject for separate task and PR.

2022-04-12 17:48 UTC, miroshnikov-spryker commented on resources/steps/checkout_steps.robot
>  Yves: select the following payment method on the checkout and go next:
40 usages + [this](https://github.com/spryker/robotframework-suite-tests/pull/123#discussion_r848111040)

2022-04-12 17:57 UTC, miroshnikov-spryker commented on resources/steps/customer_account_steps.robot
> +    Yves: go to URL:    en/customer/overview
Yes we can. But I borrowed this approach from another method and there are at least 30 of them already, so should we do it right here or in separate task for refactoring?

2022-04-12 17:58 UTC, miroshnikov-spryker commented on resources/steps/customer_account_steps.robot
>  Yves: check that user has address exists/doesn't exist:
7 usages + [this](https://github.com/spryker/robotframework-suite-tests/pull/123#discussion_r848111040)

2022-04-12 18:03 UTC, miroshnikov-spryker commented on resources/steps/payone_steps.robot
> +Payone: submit credit card form with the following data:
Ok. Can I leave Payone prefix to indicate that method is used on Payone page?

2022-04-12 18:04 UTC, miroshnikov-spryker commented on resources/steps/payone_steps.robot
> +Payone: close Beeceptor relay
Yes it will close automatically after suite is finished and I think there should be no problem to leave it running. We can delete it.

2022-04-12 18:14 UTC, miroshnikov-spryker commented on resources/steps/zed_payment_methods_steps.robot
> +Zed: activate payment method:
It is not so different in fact. 'Activate' method has more logic to ensure that payment method not only activated but also associated with the store, and 'deactivate' method just skips this part because it is not relevant there.
I made it two methods because underlying methods used here are twins too: (Zed: Check checkbox by Label:/Zed: Uncheck checkbox by Label: -> Check checkbox/Uncheck Checkbox) so we can either do the same or put several ifs. Should I rewrite?

2022-04-12 18:18 UTC, miroshnikov-spryker commented on tests/api/suite_nonsplit/glue/category_nodes.robot
> +My_first_test
Thank you for this point. I have started from Vitalii branch and just assumed that there is no test/debug things. I will check and clean.

2022-04-12 18:21 UTC, miroshnikov-spryker commented on tests/api/suite_nonsplit/glue/category_nodes.robot
> +
I think this file should be deleted, I will discuss with @vitalii-levchenko, thank you for finding it.

2022-04-12 18:30 UTC, miroshnikov-spryker commented on tests/e2e/aop/usercentrics_e2e_connect_pbc.robot
> +Usercentrics_connect_application_eves
Will remove whole file

2022-04-12 18:31 UTC, miroshnikov-spryker commented on tests/e2e/aop/usercentrics_e2e_connect_pbc.robot
> +    #открыл стейдж
Will do

2022-04-12 19:09 UTC, miroshnikov-spryker commented on resources/steps/checkout_steps.robot
> +    ...    Click    //form[@name='paymentForm']//h5[contains(text(), '${paymentProvider}')]/following::label//span[contains(text(), '${paymentMethod}')]
Payment method form has the following structure (`h5` and `ul` have no attributes at all):
```
<div class="form__container">
  <h5>Payment provider 1</h5>
  <ul>*list of payment methods for payment provider 1*</ul>
  <h5>Payment provider 2</h5>
  <ul>*list of payment methods for payment provider 2*</ul>
</div>
```
I can't think of another way to write this locator without `h5` apart from switching `h5` to `*`. Will it be better this way?

As far as I understand the syntax, `ELSE IF` on line:126 should be related to `Run Keyword If    '${env}'=='b2b'` on line:123 and if so, the logic is not added for b2b env but rather added without touching all preexisting use cases. Please correct me if I'm wrong.

2022-04-12 19:31 UTC, miroshnikov-spryker commented on resources/steps/orders_management_steps.robot
> +Yves: get the last placed order ID
`Yves: get the last placed order ID by current customer` internally uses `Yves: go to user menu item in header:` which relies on some drop-down menu in header and this menu doesn't exist in suite-nonsplit (PBCs are not integrated to demoshops yet, I think). And the structure of that method seemed already overcomplicated to me with it reliance on the dropdown menu and if-statement deciding what item should be clicked. So instead of complicating it further I decided to implement simplified version and put it where it fits the most in my opinion: steps/order_management_steps. Should I try to tweak original `Yves: get the last placed order ID by current customer` instead?

2022-04-12 19:39 UTC, miroshnikov-spryker commented on tests/e2e/aop/usercentrics_e2e_connect_pbc.robot
> +Usercentrics_connect_application_zed
Yes, I started from the existing branch of Vitalii and forgot to check for unrelated pieces. I will delete it from this PR and it will be implemented in another task.

2022-04-12 20:05 UTC, miroshnikov-spryker commented
> How long does test execution take? Can I see it in action?

Time of execution greatly varies because of async communications happening in background: message broker consumers are slow in jenkins, catching payone notifications via beeceptor is also slow, oms checks also happening in jenkins and so on. I was working on possible approaches to speed it up on local machine but without much success - this test can fail from time to time because of long waits and timeouts. I need more time to polish it before I can show the full test execution without wasting a lot of time on needless waits.

> How to prevent people from adding step definitions that already exist but are slightly different? E.g. `wait for order item to be in state` vs `wait for order item in state`?

IDE support is lacking, so I think having a list of existing methods in separate file categorized in some meaningful way will help. I checked in readme - the documentation on all methods exists can be regenerated.

> Can we run on travis as well as locally?

I think Juan Fernandez is working on the travis part right now.

2022-04-13 05:30 UTC, stereomon commented on resources/common/common.robot
> +#Migration to the Browser Library
Please clarify and add a better description

2022-04-13 05:31 UTC, stereomon commented on resources/common/common.robot
>      FOR    ${key}    ${value}    IN    &{arguments}
That's awkward. But ok.

2022-04-13 05:32 UTC, stereomon commented on resources/common/common_aop.robot
> +Library                   Browser    jsextension=${CURDIR}/../libraries/playwright/module.js
ok

2022-04-13 05:33 UTC, stereomon commented on resources/common/common_zed.robot
>  Zed: click button in Header:
If there are no conventions we have to create our own for this. We should not use sometimes this and sometimes that. Please align or write a convention others MUST follow.

2022-04-13 05:34 UTC, stereomon commented on resources/libraries/playwright/module.js
> +async function injectRequestApiIntoPage(page) {
There is an agreed .editorconfig. Please use one of the existing ones.

2022-04-13 05:35 UTC, stereomon commented on resources/steps/checkout_steps.robot
>  Yves: select the following existing address on the checkout as 'shipping' address and go next:
IMO the step definitions should be correct. When not fixing it now create a ticket. The problem is, when things like this are released it's harder to change them.

2022-04-13 05:36 UTC, stereomon commented on resources/steps/customer_account_steps.robot
> +    Yves: go to URL:    en/customer/overview
You can do that right away in this task

2022-04-13 05:37 UTC, stereomon commented on resources/steps/customer_account_steps.robot
>  Yves: check that user has address exists/doesn't exist:
How often it's used is not my concern. These definitions should be clean.

2022-04-13 05:38 UTC, stereomon commented on resources/steps/payone_steps.robot
> +Payone: submit credit card form with the following data:
IMO editing credit card data is not bound to Payone only.

2022-04-13 05:39 UTC, stereomon commented on resources/steps/zed_payment_methods_steps.robot
> +Zed: activate payment method:
They should be aligned.

2022-04-13 05:46 UTC, stereomon commented
TBH I don't like the Robot Framework much. New and weird syntax for all of us. We have mostly PHP developers that should also be able to write tests but this will now take a lot of time for everyone to learn. Not only BDD and Gherkins spec but also new language and syntax.

@AntonShopin was there a decision table that explain to me why we decided to go with Robot instead of the already used codeception? Codeception also has parallelization in place we could leverage for performance improvements.

2022-04-13 07:45 UTC, miroshnikov-spryker commented on resources/steps/customer_account_steps.robot
>  Yves: check that user has address exists/doesn't exist:
I will start a new task for refactoring and clean all related comments there. Is that ok?

2022-04-13 15:28 UTC, miroshnikov-spryker commented on resources/steps/customer_account_steps.robot
> +    Yves: go to URL:    en/customer/overview
done

2022-04-13 15:29 UTC, miroshnikov-spryker commented on resources/libraries/playwright/module.js
> +async function injectRequestApiIntoPage(page) {
Done

2022-04-13 15:30 UTC, miroshnikov-spryker commented on resources/steps/checkout_steps.robot
>  Yves: select the following existing address on the checkout as 'shipping' address and go next:
Created separate refactoring ticket

2022-04-14 22:31 UTC, AntonShopin commented on resources/common/common_yves.robot
> +Yves: get current lang
this method is not clear to me. You have 2 returns from the same keyword. Let's imagine that logo URL is `/en`

- first if will return from keyword `en` in `...    AND    return from keyword    ${currentLang}`
- second if will return from keyword `en` in `...    return from keyword    ${currentLang}`
- and at the end it will be overwritten with ${EMPTY} 

How is suppose to work? 

Also, you set suite variable, please use `Set Test Variable` instead, because in another test in the same suite you may switch to the DE version, but variable value will remain from the previous test.

2022-04-14 22:31 UTC, AntonShopin commented on resources/steps/zed_payment_methods_steps.robot
> +    Element should be visible    xpath=//div[contains(text(), 'Payment method has been successfully updated')]
please find a better way to assert that the action was successful. Maybe try to reuse `Zed: message should be shown:` as an idea. Reason to update: Zed supports not only EN version. If Zed will b in DE locale, then we'll need to find a hardcoded locator inside the keyword.

2022-04-14 22:31 UTC, AntonShopin commented on resources/steps/zed_payment_methods_steps.robot
> +Zed: activate/deactivate payment method:
Please add more flexibility here. You hardcode 2 checkboxes: DE and AT. Keyword should allow to activate/deactivate payment method per store or for both (in other words with this keyword I want to activate payment method for AT but deactivate for DE).

2022-04-15 11:04 UTC, miroshnikov-spryker commented on resources/common/common_yves.robot
> +Yves: get current lang
My assumption was that keyword will terminate after the first executed return statement. So the logic was to try to search for lang in several different sources until it is found and return it immediately and stop execution.
I just found out that lang can be extracted from <html> lang attribute, so I will rewrite it.

2022-04-15 11:51 UTC, miroshnikov-spryker commented on resources/steps/zed_payment_methods_steps.robot
> +    Element should be visible    xpath=//div[contains(text(), 'Payment method has been successfully updated')]
`Zed: message should be shown:` is doing the same thing - it checks the text of the message. Implemented new keyword that checks success message existence only.

2022-04-15 14:02 UTC, miroshnikov-spryker commented on resources/steps/zed_payment_methods_steps.robot
> +Zed: activate/deactivate payment method:
Done

2022-04-15 16:57 UTC, miroshnikov-spryker commented on resources/steps/payone_steps.robot
> +Payone: submit credit card form with the following data:
Forms for filling out credit cards can differ from each other so much that you will have to use different methods to fill in the same fields, for example, month and year can be a text field, or they can be a list; in Payone form, some inputs are in iframes. It seems to me that it would be unreasonably difficult to make one method for all credit cards.

2022-04-15 16:58 UTC, miroshnikov-spryker commented on resources/steps/zed_payment_methods_steps.robot
> +Zed: activate payment method:
Done

2022-04-15 16:59 UTC, miroshnikov-spryker commented on resources/steps/checkout_steps.robot
> +    ...    Click    //form[@name='paymentForm']//h5[contains(text(), '${paymentProvider}')]/following::label//span[contains(text(), '${paymentMethod}')]
Fixed

2022-04-15 16:59 UTC, miroshnikov-spryker commented on resources/steps/orders_management_steps.robot
> +Yves: get the last placed order ID
Fixed

2022-04-15 17:01 UTC, miroshnikov-spryker commented on resources/common/common_zed.robot
>  Zed: click button in Header:
Created another ticket for refactoring and cleanup.

2022-04-20 19:08 UTC, jfernandezsw commented on resources/steps/payone_steps.robot
> +Payone: submit credit card form with the following data:
The expression "the following" is present in many test cases, should I remove it in all of them in order to simplify the names?

2022-04-21 04:41 UTC, stereomon commented on resources/steps/payone_steps.robot
> +Payone: submit credit card form with the following data:
Yes, please simplify as much as possible.

2022-05-05 14:02 UTC, AntonShopin commented
@stereomon there was no decision table where it was decided to go with RobotFramework. When we raised the automation topic inside the ACP, we got the following feedback: 

`We don’t have those types of tests at all:
Contract tests - don’t know how to do
Performance tests - no requirements at all
UI tests on Yves - don’t know how to do
Integration tests - don’t know do we need it
Security tests - don’t know how to do`

**UI tests on Yves - don’t know how to do**

Investigate possible tools/frameworks that fit the ACP team - was one of the initiatives inside the ACP team. The result of this initiative is supposed to be a decision table with pros, cons, and team fitness. No one says that Codeception is bad and Robot is good. It should fit the team, the whole team. We should be open to new frameworks and languages. like FeS, where we use Cypress, Chromatic, and Ghost Inspector - all are new tools for us, but they are applied and bring value!

Also, we can have different tools, there will be no silver bullet that will cover all our needs in all product lines, like UI testing, Integration testing, Contract testing, API testing, Performance testing, and so on. 
Codeception might be used in ACP for API and Integration tests written by developers, QA can focus on UI tests using RobotFramework, and so on. 

RobotFramework as a Codeception can parallelize tests, can automatically rerun failed tests on CI to minimize flaky tests, and can use all power of the Playwright for Browser testing (like automatic waits, having an access to the browser storage, network and so on). It can be extended using different libraries to enable API testing, DB testing and so on.

I don't know at which point we focused only on it in this automation initiative. The discussion was to evaluate: Codeception, Cypress, RobotFramework, and other tools.

2022-05-05 14:49 UTC, AntonShopin approved these changes

2022-05-06 08:58 UTC, merged