B2b cart comments smoke test
spryker/robotframework-suite-tests pull request #358
Opened 2022-10-10 08:38 UTC by durgesh-verma-spryker

## PR Description
https://spryker.atlassian.net/browse/CC-21651

Add comments to a Cart

- As a buyer user add few comments to a Cart in Yves side, place an order and check comments appears at Order detailed page in Zed and Order detailed page in Yves

- At Yves Add, Edit, Delete comments in Cart

2022-10-31 20:02 UTC, AntonShopin requested changes
I also don't see tests for:
* View and manage comments in the order history (Yves)

2022-10-31 20:02 UTC, AntonShopin commented on tests/smoke/smoke_b2b.robot
> +    Yves: go to user menu item in the left bar:    Order History
this test looks not full. Where are assertions in Zed? 

Apply same comments from previous test, like name of the test, name of the shopping cart, 2 products, additional not needed check of the cart and item in cart

2022-11-10 14:53 UTC, durgesh-verma-spryker commented on resources/pages/yves/yves_order_details_page.robot
> +${order_details_write_comment_placeholder}    xpath=//textarea[@placeholder='Write a comment']
Fixed

2022-11-10 14:53 UTC, durgesh-verma-spryker commented on resources/pages/yves/yves_order_details_page.robot
> +${order_details_add_button}    xpath=//button[@title='Add']
Fixed

2022-11-10 14:53 UTC, durgesh-verma-spryker commented on resources/pages/yves/yves_order_details_page.robot
> +${order_details_edit_comment_placeholder}    xpath=//textarea[@required="required"]
Fixed

2022-11-10 14:53 UTC, durgesh-verma-spryker commented on resources/pages/yves/yves_order_details_page.robot
> +${order_details_edit_comment_button}    xpath=(//div[@class="grid grid--center"]//button)[1]
FIxed

2022-11-10 14:53 UTC, durgesh-verma-spryker commented on resources/pages/yves/yves_order_details_page.robot
> +${order_details_update_button}    xpath=//button[@class="button button--small js-comment-form__submit-button"]
Fixed

2022-11-10 14:53 UTC, durgesh-verma-spryker commented on resources/pages/yves/yves_order_details_page.robot
> +${yves_comment_delete_button}    xpath=(//button[contains(@action,'/comment/remove')])[1]
Fixed

2022-11-10 14:54 UTC, durgesh-verma-spryker commented on resources/pages/zed/zed_order_details_page.robot
> +${order_details_page_add_comments_textbox}    xpath=//textarea[@class="textarea textarea--cart-comment add-comment-form__textarea js-add-comment-form__textarea"]
Fixed

2022-11-10 14:54 UTC, durgesh-verma-spryker commented on resources/steps/comments_order_steps.robot
> +${zed_view_button_of_last_order}    xpath=(//a[contains(@href,'/sales/detail')])[1]
Fixed

2022-11-10 14:54 UTC, durgesh-verma-spryker commented on resources/steps/comments_order_steps.robot
> +    Type Text    ${order_details_write_comment_placeholder}    abc${random}
Fixed

2022-11-10 14:54 UTC, durgesh-verma-spryker commented on resources/steps/comments_order_steps.robot
> +       END
Fixed

2022-11-10 14:55 UTC, durgesh-verma-spryker commented on resources/steps/comments_order_steps.robot
> +    Click    ${order_details_remove_comment_button}
Fixed

2022-11-10 14:55 UTC, durgesh-verma-spryker commented on resources/steps/comments_order_steps.robot
> +*** Settings ***
Fixed

2022-11-10 14:55 UTC, durgesh-verma-spryker commented on resources/steps/zed_order_shipment_steps.robot
> +    Select From List By Text    ${shipment_method_dropdown_new_shipment_page}    DHL - Express
Fixed

2022-11-10 14:55 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +Resource    ../../resources/steps/zed_order_shipment_steps.robot
Fixed

2022-11-10 14:55 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +    ...    AND    Reload
Fixed

2022-11-10 14:56 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +    Zed: flash message should be shown:    success
Fixed

2022-11-10 14:56 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +    Yves: the following shopping cart is shown:    shoppingCartName+${random}    Owner access
Fixed

2022-11-10 14:56 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +    Yves: shopping cart contains the following products:    ${bundled_product_3_concrete_sku}
Fixed

2022-11-10 14:56 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +    Yves: create new 'Shopping Cart' with name:    shoppingCartName+${random}
Fixed

2022-11-10 14:56 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +    Yves: go to PDP of the product with sku:    ${bundled_product_2_abstract_sku
Fixed

2022-11-10 14:56 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +    Yves: adding comments on cart before checkout
Fixed

2022-11-10 14:56 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +    Yves: click on the 'Checkout' button in the shopping cart
Fixed

2022-11-10 14:56 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +    Zed: checking comments added in zed
Fixed

2022-11-10 14:57 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +At_Yves_Add_Edit_Delete_comments_in_Cart
Fixed

2022-11-10 14:57 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +    Yves: the following shopping cart is shown:    shoppingCartName+${random}    Owner access
Fixed

2022-11-10 14:57 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +    Yves: go to PDP of the product with sku:    ${bundled_product_2_abstract_sku}
Fixed

2022-11-10 14:57 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +    Yves: shopping cart contains the following products:    ${bundled_product_2_abstract_sku}
Fixed

2022-11-10 14:57 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +    Yves: add edit delete comments on cart
Fixed

2022-11-10 14:58 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +    ...    AND     Yves: logout on Yves as a customer
Fixed

2022-11-10 14:59 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +    Yves: go to user menu item in the left bar:    Order History
Fixed

2022-11-21 16:17 UTC, AntonShopin commented on resources/steps/order_comments_steps.robot
> +Yves: go to 'Order History' page to check comments:
please rename it. Order History page is a page where you see the list of all orders in a table. In your keyword, you go order details page of the last place order

2022-11-21 16:21 UTC, AntonShopin commented on resources/steps/order_comments_steps.robot
> +    ${text}    Get Text    ${comments_shopping_cart}
What is the difference between this keyword and `Yves: adding comments on cart before checkout:`?

2022-11-21 16:24 UTC, AntonShopin commented on resources/steps/order_comments_steps.robot
> +Yves:edit comments on cart:
1. Add a space after `:`
2. Why do you put everywhere 'comments' in plural? We can add multiple comments with your keywords?

2022-11-21 16:24 UTC, AntonShopin commented on resources/steps/order_comments_steps.robot
> +    Should Be Equal    ${comment}    ${text}
as above, this assertion should not be here

2022-11-21 16:25 UTC, AntonShopin commented on resources/steps/order_comments_steps.robot
> +Yves: add comment on order:
please rename it so it's clear where we add this comment.

2022-11-21 16:25 UTC, AntonShopin commented on resources/steps/order_comments_steps.robot
> +    Should Be Equal    ${comments}    ${text}
again, those assertions should not be here

2022-11-21 16:27 UTC, AntonShopin commented on tests/smoke/smoke_b2b.robot
> +    Yves: shopping cart contains the following products:    ${bundled_product_3_concrete_sku}
not fixed. I asked you to remove this step

2022-11-21 16:28 UTC, AntonShopin commented on tests/smoke/smoke_b2b.robot
> +    Yves: click on the 'Checkout' button in the shopping cart
not fixed. See my comments above about your keywords, where you have injected assertion. It should be a separate keyword

2022-11-21 16:30 UTC, AntonShopin commented on tests/smoke/smoke_b2b.robot
> +    Yves: delete comments on cart
How do you assert that a specific comment is removed? 
Cart can contain few comments, please think one more time about how to handle it in all your keywords

2022-11-21 16:31 UTC, AntonShopin commented on tests/smoke/smoke_b2b.robot
> +At_Yves_attach_few_comments_to_order_check_they_appeared_in_Zed
Test name should be changed

2022-11-24 10:30 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +    ...    AND    Reload
Fixed

2022-11-24 10:30 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +    Yves: click on the 'Checkout' button in the shopping cart
Fixed, added new keyword

2022-11-24 10:32 UTC, durgesh-verma-spryker commented on resources/pages/yves/yves_order_details_page.robot
> +${order_details_edit_comment_placeholder}    xpath=//div[starts-with(@class,"comment-form__edit js-comment__target-all")]/textarea
Fixed, as per your suggestion

2022-11-24 11:14 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +    [Documentation]    adding comments to cart
Fixed, added documentation

2022-11-24 11:14 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +    Yves: shopping cart contains the following products:    ${bundled_product_3_concrete_sku}
Removed successfully

2022-11-24 11:19 UTC, durgesh-verma-spryker commented on resources/pages/yves/yves_order_details_page.robot
> +${order_details_add_button}    xpath=//button[@class="button button--primary add-comment-form__button js-add-comment-form__button"]
Fixed, name and locators updated

2022-11-24 11:20 UTC, durgesh-verma-spryker commented on resources/pages/yves/yves_order_details_page.robot
> +${order_details_edit_comment_button}    xpath=//button[contains(@class,"col button button--hollow-icon-small js-comment__trigger-all")]
Fixed

2022-11-24 11:20 UTC, durgesh-verma-spryker commented on resources/pages/yves/yves_order_details_page.robot
> +${order_details_update_button}    xpath=//button[contains(@action,"/en/comment/update")]
Fixed, as suggested

2022-11-24 12:03 UTC, durgesh-verma-spryker commented on resources/pages/yves/yves_order_details_page.robot
> +${comments_shopping_cart}    xpath=//div[contains(@class,"comment-form__readonly js-comment__target-all")]/p
Fixed, added locators to respective page

2022-11-24 12:04 UTC, durgesh-verma-spryker commented on resources/pages/zed/zed_order_details_page.robot
> +${add_button_order_details_page}    xpath=//form[contains(@action,"/comment/add")]/button
Fixed

2022-11-24 12:04 UTC, durgesh-verma-spryker commented on resources/steps/order_comments_steps.robot
> +*** Keywords ***
Fixed, Added .

2022-11-24 12:06 UTC, durgesh-verma-spryker commented on resources/steps/order_comments_steps.robot
> +    Should Be Equal    ${comments}    ${text}
Fixed, added assertion

2022-11-24 12:07 UTC, durgesh-verma-spryker commented on resources/steps/order_comments_steps.robot
> +Yves: go to 'Order History' page to check comments:
Fixed

2022-11-24 12:07 UTC, durgesh-verma-spryker commented on resources/steps/order_comments_steps.robot
> +Zed: checking comments added in zed:
Fixed

2022-11-24 12:07 UTC, durgesh-verma-spryker commented on resources/steps/order_comments_steps.robot
> +    ${text}    Get Text    ${comments_shopping_cart}
Fixed

2022-11-24 12:07 UTC, durgesh-verma-spryker commented on resources/steps/order_comments_steps.robot
> +    ${text}    Get Text    ${comments_shopping_cart}
Fixed, removed duplicate successfully

2022-11-24 12:08 UTC, durgesh-verma-spryker commented on resources/steps/order_comments_steps.robot
> +Yves:edit comments on cart:
Fixed

2022-11-24 12:08 UTC, durgesh-verma-spryker commented on resources/steps/order_comments_steps.robot
> +    Should Be Equal    ${comment}    ${text}
Fixed, Added new keyword for assertion

2022-11-24 12:09 UTC, durgesh-verma-spryker commented on resources/steps/order_comments_steps.robot
> +Yves: add comment on order:
Fixed

2022-11-24 12:09 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +    Yves: delete comments on cart
Fixed

2022-11-24 12:09 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +At_Yves_attach_few_comments_to_order_check_they_appeared_in_Zed
Fixed

2024-01-18 13:04 UTC, closed without merging