smoke b2c- glossary create and edit scenarios
spryker/robotframework-suite-tests pull request #359
Opened 2022-10-11 06:25 UTC by khushal-rathore-metacube

https://spryker.atlassian.net/browse/CC-21835

Performed below scenarios(Glossary) for b2c smoke test:
1. Create a new glossary translation
2. Edit a glossary translation and check text change in Yves

2022-10-31 16:45 UTC, AntonShopin requested changes

2022-10-31 16:45 UTC, AntonShopin commented on resources/steps/pdp_steps.robot
> +    Click     ${pdp_add_to_cart_button}
guys, we already have a keyword for adding products to the shopping cart. Please remove it

2022-10-31 16:45 UTC, AntonShopin commented on resources/steps/zed_glossary_steps.robot
> +*** Keywords ***
please rename all keywords. Uppercase should be only the first word. 
`Zed: add details to glossary section:` instead of `Zed: Add details to glossary section:`

2022-10-31 16:45 UTC, AntonShopin commented on resources/steps/zed_glossary_steps.robot
> +    Click    ${zed_translation_edit}
Do we need it? Can we use `Zed: click Action Button in a table for row that contains:`?

2022-10-31 16:45 UTC, AntonShopin commented on resources/steps/zed_glossary_steps.robot
> +    Clear Text     ${zed_translation_DE_DE}
Not needed. By default 'Type text' default keyword first clears the text. I have not found a case in your tests when you just need to clear the text and save it, you type another text instead of exiting

2022-10-31 16:45 UTC, AntonShopin commented on resources/steps/zed_glossary_steps.robot
> +    Zed: submit the form
No hardcode. Refactor the whole keyword, it should work with arguments

2022-11-02 02:39 UTC, khushal-rathore-metacube commented on tests/smoke/smoke_b2c.robot
> +    ...    ||        Produkte erfolgreich der Wunschliste hinzugefügt-Test-${random}   |   Items added successfully-Test     ||
done

2022-11-02 02:41 UTC, khushal-rathore-metacube commented on tests/smoke/smoke_b2c.robot
> +    Zed: go to second navigation item level:    Administration    Glossary
Done

2022-11-02 02:42 UTC, khushal-rathore-metacube commented on tests/smoke/smoke_b2c.robot
> +    ...    || cart.price.test${random}       | This is a sample translation         |    Dies ist eine Beispielübersetzung       ||
Done

2022-11-02 02:42 UTC, khushal-rathore-metacube commented on tests/smoke/smoke_b2c.robot
> +    ...    AND       Reload
Done

2022-11-02 02:43 UTC, khushal-rathore-metacube commented on tests/smoke/smoke_b2c.robot
> +    Zed: Edit a glossary translation    	cart.add.items.success
Done

2022-11-02 02:43 UTC, khushal-rathore-metacube commented on tests/smoke/smoke_b2c.robot
> +    Zed: Clear text
Done

2022-11-02 07:18 UTC, khushal-rathore-metacube commented on resources/steps/zed_glossary_steps.robot
> +    Click    ${zed_translation_edit}
Done

2022-11-02 07:39 UTC, khushal-rathore-metacube commented on tests/smoke/smoke_b2c.robot
> +    Zed: submit the form
Done, we have filtered the created glossary by "zed:table should contain: " logic to filter out the created glossary

2022-11-02 07:40 UTC, khushal-rathore-metacube commented on tests/smoke/smoke_b2c.robot
> +     Yves: flash message should be shown:    success    Items added successfully-Test
Done

2022-11-02 08:58 UTC, khushal-rathore-metacube commented on resources/steps/pdp_steps.robot
> +    Click     ${pdp_add_to_cart_button}
Done

2022-11-02 08:58 UTC, khushal-rathore-metacube commented on resources/steps/zed_glossary_steps.robot
> +*** Keywords ***
Done

2022-11-02 09:09 UTC, khushal-rathore-metacube commented on resources/steps/zed_glossary_steps.robot
> +    Zed: submit the form
Done

2022-11-02 09:17 UTC, khushal-rathore-metacube commented on resources/steps/zed_glossary_steps.robot
> +    Clear Text     ${zed_translation_DE_DE}
Done

2022-11-21 14:14 UTC, AntonShopin commented on resources/steps/zed_glossary_steps.robot
> +        IF    '${key}'=='DE_DE'    Type Text    ${zed_translation_DE_DE}     ${value}
please add additional condition that value is not empty, so you 'type' something only if we have a value for it

2022-11-21 14:14 UTC, AntonShopin commented on resources/steps/zed_glossary_steps.robot
> +    Input Text     ${zed_translation_EN_US}     ${original_EN}
I don't see a sense to have this keyword. You just need to fix my comment for the `Zed: add details to glossary section:` and use it for update actions (just leave value for 'Name' empty)

2022-11-21 14:14 UTC, AntonShopin commented on tests/smoke/smoke_b2c.robot
> +    Yves: validate the page title:    ${original_EN_text}-test-${random}
I'm not sure that this test won't be flaky test. Reason: when you change something in the Backoffice (Zed) it takes some time to publish these changes on the Storefront (Yves). On local env it can be 1 second, on staging it can be one minute or vice versa. To mitigate it in another tests we use: `Yves: try reloading page if element is/not appear:`

Please think about how to make this test stable and please don't just add 'Sleep'

2022-11-21 14:18 UTC, khushal-rathore-metacube commented on tests/smoke/smoke_b2c.robot
> +    Yves: validate the page title:    ${original_EN_text}-test-${random}
Sure..will do the changes

2022-11-23 09:47 UTC, khushal-rathore-metacube commented on resources/pages/yves/yves_overview_page.robot
> +${overview_page_title_locator}    xpath=//h1[@class='title title--account-main title--medium']
Fixed

2022-11-23 09:48 UTC, khushal-rathore-metacube commented on resources/steps/zed_glossary_steps.robot
> +    Zed: click Action Button in a table for row that contains:    ${glossary_name}    Edit
Fixed

2022-11-23 11:40 UTC, khushal-rathore-metacube commented on resources/steps/zed_glossary_steps.robot
> +        IF    '${key}'=='DE_DE'    Type Text    ${zed_translation_DE_DE}     ${value}
Fixed

2024-01-18 13:04 UTC, closed without merging