smoke b2c pdp scenario
spryker/robotframework-suite-tests pull request #360
Opened 2022-10-12 14:33 UTC by khushal-rathore-metacube

https://spryker.atlassian.net/browse/CC-21837

Written only add product to cart and add to wishlist scenario as remaining scenarios are covered in existing test cases in smoke b2c with below mentioned test cases names:

1. Product_labels
2. Product_PDP
3.  Product_Relations
4. Product_Sets
5. Product_Bundles
6. Catalog_Actions

2022-10-31 16:26 UTC, AntonShopin requested changes
Could you please point me out which tests we already check: 
* User can see product groups (PDP)
* Verify PDP of a product set → User can add individual product to cart
* Verify PDP of a product: images, product description

2022-10-31 16:26 UTC, AntonShopin commented on tests/smoke/smoke_b2c.robot
> +    Yves: add product to wishlist:    My wishlist
where are the assertions? How do you make sure that the right variant was added to the shopping cart and wishlist and is displayed there?

2022-11-08 07:14 UTC, khushal-rathore-metacube commented on tests/smoke/smoke_b2c.robot
> +    Yves: add product to wishlist:    My wishlist
Done, fixed

2022-11-08 07:15 UTC, khushal-rathore-metacube commented
Covered below scenarios:
User can see product groups (PDP)
Verify PDP of a product set → User can add individual product to cart
Verify PDP of a product: images, product description

2024-01-18 13:04 UTC, closed without merging