added missing logic in User_account test
spryker/robotframework-suite-tests pull request #361
Opened 2022-10-13 07:43 UTC by himanshu-pal-metacube

added Logic for Addresses, My Profile, Returns, Overview, Newsletter in common_yves.robot

2022-10-31 16:06 UTC, AntonShopin requested changes

2022-10-31 16:06 UTC, AntonShopin commented on resources/pages/yves/yves_header_section.robot
> +${my_profile_page_locator}    xpath=//a[@class='button button--expand-sm-only button--alert button--hollow']
you can't put locators from different pages into one, especially which describes totally another area. 
If some pages don't exist, like 'Newsletter' - don't be afraid to create it. OK if it will contain only one main locator, later we can extend it. Same for all other locators/pages. 

The overview locator should be inside the overview page, newsletter locator -> newsletter page, and so on

2022-11-03 10:58 UTC, himanshu-pal-metacube commented on resources/pages/yves/yves_header_section.robot
> +${my_profile_page_locator}    xpath=//a[@class='button button--expand-sm-only button--alert button--hollow']
I removed the locators and added new logic `Yves: assertion of page title:` to validate the page tittle.

2022-11-21 13:33 UTC, AntonShopin commented on resources/common/common_yves.robot
> +    Should Contain    ${title}    ${page_name}
1. Please rename it. It should sound like an action, f.e.  `Yves: page title should contain:`
2. Does it work? I thought that it's required to have '=' sign, like: `${title}=    Get Title`

2022-11-22 19:18 UTC, himanshu-pal-metacube commented on resources/common/common_yves.robot
> +    Should Contain    ${title}    ${page_name}
1. Renamed.
2. Yes, it works without '=' sign. But as you suggested I added '=' sign.

2024-01-18 13:04 UTC, closed without merging