b2c all available stores are displayed in the grid
spryker/robotframework-suite-tests pull request #362
Opened 2022-10-14 09:51 UTC by khushal-rathore-metacube

https://spryker.atlassian.net/browse/CC-21838

 all available stores are displayed in the grid

2022-10-31 16:00 UTC, AntonShopin requested changes

2022-10-31 16:00 UTC, AntonShopin commented on resources/environments/environments_b2c.json
> +        "store_DE":"DE"
it's a name or store id?

2022-10-31 16:00 UTC, AntonShopin commented on resources/pages/zed/zed_administration_page.robot
> +${administration_store_id_2_locator}    xpath=//tr[@class='even']//td[contains(@class,'column-id_store')]
* such a page doesn't exist. We have a 'Stores' page but not 'Administration'
* what if we'll have 10 stores. Do we need to create locators for them as they are dynamic? It's just a common Zed table, I don't see a need to describe exactly this specific table

2022-10-31 16:00 UTC, AntonShopin commented on resources/steps/zed_administration_steps.robot
> +    Element Text Should Be    ${administration_store_id_2_locator}    DE
* You hardcoded expected values
* you use specific locators for 2 stores, don't do this. Stores are dynamic, reuse `Zed: table should contain:` or `Zed: table should contain non-searchable value:` with arguments in this keyword

2022-10-31 16:00 UTC, AntonShopin commented on tests/smoke/smoke_b2c.robot
> +    Zed: go to second navigation item level:    Administration    Stores
why do first you try to go to Administration (not existing) page and in the next step you go in the right way?

2022-11-03 05:05 UTC, khushal-rathore-metacube commented on resources/steps/zed_administration_steps.robot
> +    Element Text Should Be    ${administration_store_id_2_locator}    DE
Done

2022-11-03 05:06 UTC, khushal-rathore-metacube commented on tests/smoke/smoke_b2c.robot
> +    Zed: go to second navigation item level:    Administration    Stores
Done..fixed

2022-11-03 05:06 UTC, khushal-rathore-metacube commented on resources/environments/environments_b2c.json
> +        "store_DE":"DE"
fixed

2022-11-03 05:07 UTC, khushal-rathore-metacube commented on resources/pages/zed/zed_administration_page.robot
> +${administration_store_id_2_locator}    xpath=//tr[@class='even']//td[contains(@class,'column-id_store')]
fixed

2022-11-21 13:26 UTC, AntonShopin commented on resources/steps/zed_administration_steps.robot
> +Zed: check the avaialbe Stores:
typo in `avaialbe`

2022-11-22 10:52 UTC, khushal-rathore-metacube commented on resources/environments/environments_b2c.json
> +        "store_name_2":"DE"
Fixed

2022-11-22 10:53 UTC, khushal-rathore-metacube commented on resources/steps/zed_administration_steps.robot
> +Zed: check the avaialbe Stores:
Fixed

2022-11-22 17:30 UTC, AntonShopin approved these changes

2022-11-23 07:39 UTC, khushal-rathore-metacube commented
Conflicts has been resolved

2024-01-18 13:04 UTC, closed without merging