smoke_b2b_merchant_relation_test
spryker/robotframework-suite-tests pull request #363
Opened 2022-10-17 11:15 UTC by durgesh-verma-spryker

## PR Description
https://spryker.atlassian.net/browse/CC-21651

smoke_b2b_merchant_relation_test
Merchant relations in Zed 
- Create a merchant
- Create a merchant relation between a BU of a company and the merchant

2022-10-31 15:51 UTC, AntonShopin requested changes

2022-10-31 15:51 UTC, AntonShopin commented on resources/pages/zed/zed_create_merchant_page.robot
> +${merchant_checkbox_de_locator}    id=merchant_storeRelation_id_stores_1
Please check already existing keywords and tests for merchants in Zed. 
https://github.com/spryker/robotframework-suite-tests/blob/master/tests/smoke/smoke_mp_b2b.robot#L1003
I can't get why we need to create all these new locators

2022-10-31 15:51 UTC, AntonShopin commented on resources/steps/merchant_steps.robot
> +    Check Checkbox    ${merchant_checkbox_de_locator}
Please check already existing keywords and tests for merchants in Zed. 
https://github.com/spryker/robotframework-suite-tests/blob/master/tests/smoke/smoke_mp_b2b.robot#L1003
I can't get why we need to create new keyword instead of using existing one

2022-10-31 15:51 UTC, AntonShopin commented on resources/steps/merchant_steps.robot
> +    Click    ${dropdown_value_Computer_locator}
how do you think that I don't like in this keyword? 

Why do you hardcode everything :(

2022-10-31 15:51 UTC, AntonShopin commented on tests/smoke/smoke_b2b.robot
> +   ...    AND       Reload
Please check already existing keywords and tests for merchants in Zed. 
https://github.com/spryker/robotframework-suite-tests/blob/master/tests/smoke/smoke_mp_b2b.robot#L1003

2022-10-31 15:51 UTC, AntonShopin commented on tests/smoke/smoke_b2b.robot
> +Create_a_merchant_relation_between_a_BU_of_a_company_and_the_merchant
* add [Documentation] 
* Each test should be atomic as much as possible. If you would like to create a new merchant relation - create in your test in a [Setup] new merchant and only then create a relation with it. In the [teardown] - delete this merchant relation and deactivate a merchant.

2022-10-31 15:51 UTC, AntonShopin commented on tests/smoke/smoke_b2b.robot
> +   Zed: Create Merchant Relation between a BU of a company and the merchant
Fully hardcoded. Please refactor

2022-10-31 15:51 UTC, AntonShopin commented on tests/smoke/smoke_b2b.robot
> +   Zed: submit the form
where are the assertions? How do you make sure that the relation has been created?

2022-10-31 15:51 UTC, AntonShopin commented on resources/pages/zed/zed_merchant_relation_page.robot
> +${merchant_dropdown_locator}    xpath=(//span[@class='select2-selection__arrow'])[1]
this span has an id, why do you put class and rely on position? This is mad

2022-10-31 15:51 UTC, AntonShopin commented on resources/pages/zed/zed_merchant_relation_page.robot
> +${company_dropdown_locator}    xpath=//span[@Title='Select Company']
same here. This dropdown has an id, why do you use 'title'?

2022-10-31 15:51 UTC, AntonShopin commented on resources/pages/zed/zed_merchant_relation_page.robot
> +${Assigned_product_lists_locator}    xpath=(//span[@role='combobox'])[5]
* why do locators start from the uppercase?
* I can't get these locators. @role ... [3],[4],[5] - what is this for? Please create normal locators

2022-10-31 15:51 UTC, AntonShopin commented on resources/pages/zed/zed_merchant_relation_page.robot
> +${dropdown_value_Computer_locator}    xpath=//li[@class="select2-results__option" and contains(text(),'Computer')]
* which drawdown? store dropdown, price type dropdown, business unit, company ...?  
* I see 0 matches for these locators, do they work?

2022-11-08 06:40 UTC, durgesh-verma-spryker commented on resources/pages/zed/zed_create_merchant_page.robot
> +${merchant_checkbox_de_locator}    id=merchant_storeRelation_id_stores_1
- We did not found such locators though created new one.
- Fixed.

2022-11-08 06:41 UTC, durgesh-verma-spryker commented on resources/steps/merchant_steps.robot
> +    Check Checkbox    ${merchant_checkbox_de_locator}
Fixed

2022-11-08 06:42 UTC, durgesh-verma-spryker commented on resources/steps/merchant_steps.robot
> +    Click    ${dropdown_value_Computer_locator}
Fixed as you suggested

2022-11-08 06:42 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +   ...    AND       Reload
Fixed

2022-11-08 06:43 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +   Zed: submit the form
Fixed

2022-11-08 06:43 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +   Zed: Create Merchant Relation between a BU of a company and the merchant
Fixed

2022-11-08 06:44 UTC, durgesh-verma-spryker commented on resources/pages/zed/zed_merchant_relation_page.robot
> +${Assigned_product_lists_locator}    xpath=(//span[@role='combobox'])[5]
Fixed

2022-11-08 06:46 UTC, durgesh-verma-spryker commented on resources/pages/zed/zed_merchant_relation_page.robot
> +${dropdown_value_Computer_locator}    xpath=//li[@class="select2-results__option" and contains(text(),'Computer')]
Fixed

2022-11-08 09:39 UTC, durgesh-verma-spryker commented on resources/pages/zed/zed_merchant_relation_page.robot
> +${company_dropdown_locator}    xpath=//span[@Title='Select Company']
Fixed.

2022-11-08 09:40 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +Create_a_merchant_relation_between_a_BU_of_a_company_and_the_merchant
Fixed

2022-11-08 09:41 UTC, durgesh-verma-spryker commented on resources/pages/zed/zed_merchant_relation_page.robot
> +${company_dropdown_locator}    xpath=//span[@Title='Select Company']
Fixed

2022-11-08 09:45 UTC, durgesh-verma-spryker commented on resources/pages/zed/zed_merchant_relation_page.robot
> +${merchant_dropdown_locator}    xpath=(//span[@class='select2-selection__arrow'])[1]
Tried using id but did not got result so used xpath.I tried using select by value, text,label and here I used locator by ID of span(id=select2-merchant-relationship_fk_merchant-container), then I used xpath=//label[@for="merchant-relationship_fk_merchant"]//following-sibling::span//span[@class="select2-selection__arrow"] by using this I was able to click on this element.

2022-11-18 10:40 UTC, AntonShopin commented on resources/pages/zed/zed_merchant_relation_page.robot
> +${assigned_bussiness_units_locator}    xpath=//span[@data-select2-id="7"]
Please change the locator. What I don't like is an unknown id=7. 
Please check, maybe this one would be better? `//form[@name='merchant-relationship']//*[contains(@name,'assigneeCompanyBusinessUnit')]/following-sibling::span`

2022-11-18 10:40 UTC, AntonShopin commented on resources/pages/zed/zed_merchant_relation_page.robot
> +${assigned_product_lists_locator}    xpath=//span[@data-select2-id="8"]
Maybe this one would be better? `//form[@name='merchant-relationship']//*[contains(@name,'productListId')]/following-sibling::span`

2022-11-18 10:40 UTC, AntonShopin commented on resources/pages/zed/zed_merchant_relation_page.robot
> +${input_field_locator}    xpath=//input[@class="select2-search__field"]
This locator returns 2 matches (for business units and product lists). Does it work?

2022-11-18 10:40 UTC, AntonShopin commented on resources/steps/zed_marketplace_steps.robot
> +    Check Checkbox    ${merchant_is_active_checkbox_locator}
please don't do this. 
Now by default, all new merchants will be created as 'Active'. In other tests (Marketplace tests) we create merchants and check that they are created Inactive by default. 
With your checks other tests (marketplace tests) will start to fail. 
Example of such tests
``` Zed: login on Zed with provided credentials:    ${zed_admin_email}
    Zed: create new Merchant with the following data:
    ...    || merchant name        | merchant reference            | e-mail                      | store | store | en url                  | de url                  ||
    ...    || NewMerchant${random} | NewMerchantReference${random} | merchant+${random}@test.com | DE    | DE    | NewMerchantURL${random} | NewMerchantURL${random} ||
    Zed: perform search by:    NewMerchant${random}
    Zed: table should contain non-searchable value:    Inactive
    Zed: table should contain non-searchable value:    Waiting for Approval
    Zed: table should contain non-searchable value:    DE
    Zed: click Action Button in a table for row that contains:    NewMerchant${random}    Activate
    Zed: click Action Button in a table for row that contains:    NewMerchant${random}    Approve Access
 ```

2022-11-21 10:14 UTC, durgesh-verma-spryker commented on resources/pages/zed/zed_merchant_relation_page.robot
> +${input_field_locator}    xpath=//input[@class="select2-search__field"]
yes it works. Now I have fixed and used appropriate one as per your suggestion

2022-11-21 10:14 UTC, durgesh-verma-spryker commented on resources/pages/zed/zed_merchant_relation_page.robot
> +${assigned_product_lists_locator}    xpath=//span[@data-select2-id="8"]
Fixed

2022-11-21 10:14 UTC, durgesh-verma-spryker commented on resources/pages/zed/zed_merchant_relation_page.robot
> +${assigned_bussiness_units_locator}    xpath=//span[@data-select2-id="7"]
Fixed

2022-11-21 10:23 UTC, durgesh-verma-spryker commented on resources/steps/zed_marketplace_steps.robot
> +    Check Checkbox    ${merchant_is_active_checkbox_locator}
By default active one removed, and fixed

2022-11-22 17:26 UTC, AntonShopin commented on tests/smoke/smoke_b2b.robot
> +    Zed: go to second navigation item level:    Marketplace    Merchant Relations
This step is not needed as already present In `Zed: verify merchant relation`

2022-11-22 17:49 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +    Zed: go to second navigation item level:    Marketplace    Merchant Relations
successfully removed the step

2024-01-18 13:04 UTC, closed without merging