b2c warehouse scenarios
spryker/robotframework-suite-tests pull request #365
Opened 2022-10-18 07:16 UTC by khushal-rathore-metacube

https://spryker.atlassian.net/browse/CC-21836

Covered smoke b2c warehouse scenarios:

1. Create new warehouse
2. Edit warehouse
3. View warehouse
4. Set stock for new warehouse → Check in Yves
5. Deactivate warehouse 
6. Unset warehouse for store

2022-10-31 15:25 UTC, AntonShopin requested changes
you have not covered main functionality of the warehouses. 
* Warehouse can be active or no and can relate to different stores. 
* Product can have 1 or more warehouses. Like warehouse1 (DE, AT) and warehouse2 (DE only). In this case product availability for DE store is calculated taking into account BOTH warehouses

* You need to create a new warehouse 
* Check its state (status and store relation in a table)
* Edit product so it has stock quantity only in the new warehouse. For all other warehouses you need to set 0 and uncheck never out of stock (please use product, which is not used by other tests)
* Now this product fully depends on your new warehouse and you can control its availability 
* Try to add to the cart more that is specified in Zed for this product (never out of stock should be unchecked) - see an error 
* Add to cart less than specified in Zed - success. Don't place an order
* Edit in Zed warehouse - deactivate it -> check in Zed that the status has been changed in a table
* Check on Yves that the product is not available anymore
* In Zed activate warehouse - go to Yves and check that product is available again 
* Go to Zed and edit store relation, leave on;y AT, remove DE relation -> check that store relation is changed in a table
* Go to Yves -> check that product is not available anymore 
* With a teardown - return back initial state stock state of the product and deactivate newly created warehouse. 

I am supposed to do the code review and not write and explain how to test features :(

2022-10-31 15:25 UTC, AntonShopin commented on tests/smoke/smoke_b2c.robot
> +    Zed: perform search by:    ${random}
Please add something to names, not just random. I mean at least `NewWarehouse${random}`

2022-10-31 15:25 UTC, AntonShopin commented on tests/smoke/smoke_b2c.robot
> +    Zed: Navigate to view mode
* see previous comments on this keyword
* if you just view it - at least add some assertions that the content is shown, or the exact name or value is displayed. If you click on 'View' and there is an exception - your current tests won't detect it

2022-10-31 15:25 UTC, AntonShopin commented on tests/smoke/smoke_b2c.robot
> +    Zed: submit the form
also please combine these steps in a new keyword with arguments + add assertions, that warehouse status is changed in the table

2022-10-31 15:25 UTC, AntonShopin commented on tests/smoke/smoke_b2c.robot
> +    Zed: submit the form
these steps also should be combined and without hardcoded values for stock quantity and warehouse

2022-10-31 15:25 UTC, AntonShopin commented on tests/smoke/smoke_b2c.robot
> +    Yves: flash message should be shown:    error    Item 009_30692991 only has availability of 5.
are you sure that it will pass? 
What I see from your test:
* you create a warehouse 
* you edit it -> set as inactive
* you go to product and edit warehouse value to unknow warehouse and then on Yves you expect that it will fail with an error. 

From what I see, product 009 has 'never out of stock' checked in Warehouse1, which belongs to DE store. Your changes will not affect its availability in DE store. These steps will fail
*

2022-10-31 15:25 UTC, AntonShopin commented on tests/smoke/smoke_b2c.robot
> +    zed: edit warehouse
never edit the default warehouse as other thinks, like customers, users etc. If your test will fail - other tests that will expect default warehouse will also fail

2022-11-05 09:41 UTC, khushal-rathore-metacube commented on tests/smoke/smoke_b2c.robot
> +Warehouse_create_edit_view_set_stock_deactivate_warehouse_scenarios
Done

2022-11-05 09:41 UTC, khushal-rathore-metacube commented on tests/smoke/smoke_b2c.robot
> +    Zed: go to first navigation item level:    Administration
fixed

2022-11-05 09:41 UTC, khushal-rathore-metacube commented on tests/smoke/smoke_b2c.robot
> +    Zed: submit the form
Done

2022-11-05 09:42 UTC, khushal-rathore-metacube commented on tests/smoke/smoke_b2c.robot
> +    Zed: perform search by:    ${random}
done

2022-11-05 12:07 UTC, khushal-rathore-metacube commented on resources/pages/zed/zed_product_page.robot
> +${zed_product_stock_quantity_field}   id=product_concrete_form_edit_price_and_stock_0_quantity
deleteds this page

2022-11-05 12:08 UTC, khushal-rathore-metacube commented on resources/pages/zed/zed_warehouse_page.robot
> +${zed_warehouse_edit_button}    xpath=//a[contains(@href,'/stock-gui/edit')]
Done

2022-11-05 12:08 UTC, khushal-rathore-metacube commented on resources/steps/zed_product_steps.robot
> +Zed: navigate to edit page of product from product listing page
fixed

2022-11-05 12:08 UTC, khushal-rathore-metacube commented on resources/steps/zed_product_steps.robot
> +Zed: edit product details
fixed

2022-11-05 12:08 UTC, khushal-rathore-metacube commented on resources/steps/pdp_steps.robot
> +    Click    ${pdp_add_to_cart_button}
fixed

2022-11-05 12:08 UTC, khushal-rathore-metacube commented on resources/steps/zed_product_steps.robot
> +    Input Text    ${zed_product_stock_quantity_field}   5
fixed

2022-11-05 12:09 UTC, khushal-rathore-metacube commented on resources/steps/zed_product_steps.robot
> +    Zed: submit the form
fixed

2022-11-05 12:09 UTC, khushal-rathore-metacube commented on resources/steps/zed_warehouse_steps.robot
> +    Type Text    ${zed_warehouse_name}    ${name}
fixed

2022-11-05 12:09 UTC, khushal-rathore-metacube commented on resources/steps/zed_warehouse_steps.robot
> +    Click    ${zed_warehouse_edit_button}
fixed

2022-11-05 12:09 UTC, khushal-rathore-metacube commented on resources/steps/zed_warehouse_steps.robot
> +    IF  '${type}' == 'no'  Click   ${zed_warehouse_not_avaialbe_radio_button}
fixed

2022-11-05 12:09 UTC, khushal-rathore-metacube commented on resources/steps/zed_warehouse_steps.robot
> +    Zed: submit the form
fixed

2022-11-05 12:10 UTC, khushal-rathore-metacube commented on tests/smoke/smoke_b2c.robot
> +    Zed: Navigate to view mode
fixed

2022-11-05 12:10 UTC, khushal-rathore-metacube commented on tests/smoke/smoke_b2c.robot
> +    Zed: submit the form
fixed

2022-11-05 12:10 UTC, khushal-rathore-metacube commented on tests/smoke/smoke_b2c.robot
> +    Zed: submit the form
fixed

2022-11-05 12:10 UTC, khushal-rathore-metacube commented on tests/smoke/smoke_b2c.robot
> +    Yves: flash message should be shown:    error    Item 009_30692991 only has availability of 5.
fixed

2022-11-05 12:10 UTC, khushal-rathore-metacube commented on tests/smoke/smoke_b2c.robot
> +    zed: edit warehouse
fixed

2022-11-05 12:11 UTC, khushal-rathore-metacube commented on tests/smoke/smoke_b2c.robot
> +    Zed: perform search by:    009
fixed

2022-11-05 12:12 UTC, khushal-rathore-metacube commented on resources/pages/zed/zed_product_page.robot
> +${zed_product_edit_button}   xpath=//a[contains(@href,'product-management/edit')]
Done

2022-11-17 10:40 UTC, AntonShopin commented on resources/steps/zed_warehouse_steps.robot
> +    Zed: table should contain non-searchable value:    ${store}
this assertion is not correct. What if the store will be related to AT and DE, but with your tests, you expect that it's related only to AT store? With the current implementation, it will pass, which is not correct

2022-11-17 10:40 UTC, AntonShopin commented on tests/smoke/smoke_b2c.robot
> +    Yves: add product to the shopping cart
does it work? I thought that if the product is not available -> its 'Add to cart' button is not displayed or is inactive, meaning that you can't click on it and it fails. Have I missed something?

2022-11-17 10:40 UTC, AntonShopin commented on tests/smoke/smoke_b2c.robot
> +    Zed: update stock quantity of product for selected warehouse:    wareshouse${random}    ${abstract_product_sku}    ${concrete_product_sku}      ${product_quantity}
In the demo data this product has quantity 20 for Warehouse1, which is related to DE store. Why you don't update it? In my previous CR I wrote: 

> Edit product so it has stock quantity only in the new warehouse. For all other warehouses you need to set 0 and uncheck never out of stock (please use product, which is not used by other tests)

Did you ignore it?

2022-11-21 13:08 UTC, khushal-rathore-metacube commented on resources/steps/zed_product_steps.robot
> +*** Settings ***
Fixed

2022-11-21 13:13 UTC, khushal-rathore-metacube commented on resources/steps/zed_warehouse_steps.robot
> +    IF  '${type}' == 'False'  Click   ${zed_warehouse_not_avaialbe_radio_button}
Fixed

2022-11-24 08:22 UTC, khushal-rathore-metacube commented on resources/steps/zed_warehouse_steps.robot
> +Zed: activate/deactivate warehouse:
Fixed

2022-11-24 08:22 UTC, khushal-rathore-metacube commented on resources/steps/zed_warehouse_steps.robot
> +    Zed: Check checkbox by Label:    AT
Fixed

2022-11-24 08:23 UTC, khushal-rathore-metacube commented on resources/steps/zed_warehouse_steps.robot
> +    Zed: set the status of warehouse as 'Active':    True
Fixed

2022-11-25 04:12 UTC, khushal-rathore-metacube commented on tests/smoke/smoke_b2c.robot
> +    Zed: update stock quantity of product for selected warehouse:    wareshouse${random}    ${abstract_product_sku}    ${concrete_product_sku}      ${product_quantity}
Fixed

2022-11-25 04:13 UTC, khushal-rathore-metacube commented on resources/steps/zed_warehouse_steps.robot
> +    Zed: Check checkbox by Label:    ${store_1}
Fixed

2022-11-25 04:13 UTC, khushal-rathore-metacube commented on resources/steps/zed_warehouse_steps.robot
> +    Zed: Check checkbox by Label:    AT
Fixed

2022-11-25 06:28 UTC, khushal-rathore-metacube commented on tests/smoke/smoke_b2c.robot
> +    Yves: add product to the shopping cart
Fixed

2022-11-25 06:57 UTC, khushal-rathore-metacube commented on resources/environments/environments_b2c.json
> +        "product_quantity":"5"
Fixed

2022-11-25 06:57 UTC, khushal-rathore-metacube commented on resources/steps/zed_product_steps.robot
> +    [Arguments]    ${warehouse}    ${abstract_sku}    ${concrete_sku}    ${quantity}
Fixed

2022-11-25 10:59 UTC, khushal-rathore-metacube commented on resources/steps/zed_warehouse_steps.robot
> +    Zed: table should contain non-searchable value:    ${store}
Fixed

2024-01-18 13:04 UTC, closed without merging