smoke b2c user and agent failed attempts to login
spryker/robotframework-suite-tests pull request #367
Opened 2022-10-19 11:15 UTC by khushal-rathore-metacube

Performed smoke b2c failed attempts for user and agent login:
Block login after X failed attempts

1. As customer - Try to login with false password but existing email for 10 times. Check that after the 10th attempt user sees an error message and cannot login even with proper credentials for 5 minutes. Try to login after 5 minutes with correct credentials - it should be successful
2. As agent - Try to login with false password but existing email for 9 times. Check that after the 9th attempt user sees an error message and cannot login even with proper credentials for 6 minutes. Try to login after 5 minutes with correct credentials - it should be successful

2022-10-30 21:38 UTC, AntonShopin requested changes

2022-10-30 21:38 UTC, AntonShopin commented on resources/common/common_yves.robot
> +    END
These 2 keywords should not be in the common file. 
Create a new file for them, f.e. 'login_steps.robot'

Rename them - your main idea is that you run them in a loop and fail the login due to password, so no need to expect the password argument (put the value for the password in arguments: `[Arguments]    ${email}    ${password}=${random}`

2022-10-30 21:38 UTC, AntonShopin commented on resources/common/common_yves.robot
> +    Click    ${form_login_button}
also looks like it's better to move it to a separate file for login steps

2022-10-30 21:38 UTC, AntonShopin commented on resources/common/common_yves.robot
> +    Should Contain    ${url}    /agent/login_check
Please rename them as it's not clear what they do. 
Also should be moved to a separate file with steps for login as they are super specific with hardcoded expected URL values

2022-10-30 21:38 UTC, AntonShopin commented on resources/environments/environments_b2c.json
> +        "yves_agent_user_email": "agent+77359@spryker.com",
`agent+77359@spryker.com` - where it comes from? I don't remember that we have this user in the demodata

2022-10-30 21:38 UTC, AntonShopin commented on resources/environments/environments_b2c.json
> +        "yves_agent_user_password": "change123"
same here

2022-10-30 21:38 UTC, AntonShopin commented on tests/smoke/smoke_b2c.robot
> +    Yves:login on yves with invalid password:    ${yves_user_email}    ${random}
never 'block' users from the demodata, that are used by other tests! Find another user (not used by autotests) -> add it to the environment file and use it in your test

2022-10-30 21:38 UTC, AntonShopin commented on tests/smoke/smoke_b2c.robot
> +    Yves: login on Yves with provided credentials:    ${yves_user_email}
we can't wait for 5 mins in tests. 
Remove these checks and add another one, that after we have failed 10 attempts to login - you just can't to log in with valid credentials

2022-10-30 21:38 UTC, AntonShopin commented on tests/smoke/smoke_b2c.robot
> +    Open Browser
Please remove it, we already have an opened browser ;)

2022-10-30 21:38 UTC, AntonShopin commented on tests/smoke/smoke_b2c.robot
> +    Yves: go to URL:    /agent/login
you have created 2 new keywords for agent login and both contain step with `Yves: go to URL:    /agent/login`. Do we need it here?

2022-10-30 21:38 UTC, AntonShopin commented on tests/smoke/smoke_b2c.robot
> +    Yves:agent login with invalid password:    ${yves_agent_user_email}    ${random}
see the comment in keywords file

2022-10-30 21:38 UTC, AntonShopin commented on tests/smoke/smoke_b2c.robot
> +    Pause Execution
`Pause Execution` ? What is the logic?

2022-10-30 21:38 UTC, AntonShopin commented on tests/smoke/smoke_b2c.robot
> +    Yves: agent login with proper credentials:    ${yves_agent_user_email}    ${yves_agent_user_password}
we can't wait for 5 mins in tests.
Remove these checks and add another one, that after we have failed 9 attempts to login - you just can't to log in with valid credentials

2022-11-04 12:59 UTC, khushal-rathore-metacube commented on resources/common/common_yves.robot
> +    END
Done

2022-11-04 13:00 UTC, khushal-rathore-metacube commented on resources/common/common_yves.robot
> +    Click    ${form_login_button}
Done

2022-11-04 13:00 UTC, khushal-rathore-metacube commented on resources/common/common_yves.robot
> +    Should Contain    ${url}    /agent/login_check
done

2022-11-04 13:00 UTC, khushal-rathore-metacube commented on resources/environments/environments_b2c.json
> +        "yves_agent_user_email": "agent+77359@spryker.com",
Done, removed

2022-11-04 13:08 UTC, khushal-rathore-metacube commented on tests/smoke/smoke_b2c.robot
> +    Yves:login on yves with invalid password:    ${yves_user_email}    ${random}
done, created a new user: oslo test

2022-11-04 13:08 UTC, khushal-rathore-metacube commented on tests/smoke/smoke_b2c.robot
> +    Yves: login on Yves with provided credentials:    ${yves_user_email}
done

2022-11-04 13:08 UTC, khushal-rathore-metacube commented on tests/smoke/smoke_b2c.robot
> +    Open Browser
done

2022-11-04 13:09 UTC, khushal-rathore-metacube commented on tests/smoke/smoke_b2c.robot
> +    Yves: go to URL:    /agent/login
removed

2022-11-04 13:09 UTC, khushal-rathore-metacube commented on tests/smoke/smoke_b2c.robot
> +    Yves:agent login with invalid password:    ${yves_agent_user_email}    ${random}
done

2022-11-04 13:09 UTC, khushal-rathore-metacube commented on tests/smoke/smoke_b2c.robot
> +    Pause Execution
removed

2022-11-04 13:09 UTC, khushal-rathore-metacube commented on tests/smoke/smoke_b2c.robot
> +    Yves: agent login with proper credentials:    ${yves_agent_user_email}    ${yves_agent_user_password}
done

2022-11-14 07:09 UTC, khushal-rathore-metacube commented on resources/environments/environments_b2c.json
> +        "yves_agent_user_password": "change123"
done

2022-11-17 09:08 UTC, AntonShopin commented on resources/steps/yves_login_steps.robot
> +Yves: login with invalid password:
In my previous CR, I've asked to rename the keyword. It's not done. 
`Yves: login with invalid password:` how you can understand from this name that it will automatically try to log in 10 times?

2022-11-17 09:08 UTC, AntonShopin commented on resources/steps/yves_login_steps.robot
> +Yves: login with invalid agent password:
Same here, please rename it as I've requested before. It should be clear that it automatically tries to login in a loop

2022-11-17 09:08 UTC, AntonShopin commented on resources/steps/yves_login_steps.robot
> +Yves: error message should be shown:
This keyword is specific for only blocked login. The current name is too general, meaning that someone can try to use it in another test, for example, to expect an error that the product is not added to the cart, or that the Authentication failed

2022-11-17 09:08 UTC, AntonShopin commented on tests/smoke/smoke_b2c.robot
> +    Zed: create new Zed user with the following data:    agent+${random}@spryker.com    change${random}    Agent    Assist    Root group    This user is an agent    en_US
please add something unique for new agent user, like the feature that is under the test, like: `login+agent+${random}@spryker.com`

2022-11-18 07:56 UTC, khushal-rathore-metacube commented on resources/environments/environments_b2c.json
> +        "yves_third_user_password": "change123"
Fixed

2022-11-18 07:58 UTC, khushal-rathore-metacube commented on resources/pages/yves/yves_login_page.robot
> +${login_error_message_header}    xpath=//div[@class='box']//h1
fixed

2022-11-18 08:00 UTC, khushal-rathore-metacube commented on resources/steps/yves_login_steps.robot
> +Yves: login with invalid password:
fixed

2022-11-18 08:01 UTC, khushal-rathore-metacube commented on resources/steps/yves_login_steps.robot
> +Yves: login with invalid agent password:
fixed

2022-11-18 08:01 UTC, khushal-rathore-metacube commented on resources/steps/yves_login_steps.robot
> +Yves: error message should be shown:
fixed

2022-11-18 08:06 UTC, khushal-rathore-metacube commented on tests/smoke/smoke_b2c.robot
> +    Zed: create new Zed user with the following data:    agent+${random}@spryker.com    change${random}    Agent    Assist    Root group    This user is an agent    en_US
fixed

2022-11-22 17:15 UTC, AntonShopin approved these changes

2024-01-18 13:04 UTC, closed without merging