smoke b2c user control functionality
spryker/robotframework-suite-tests pull request #368
Opened 2022-10-20 10:51 UTC by khushal-rathore-metacube

https://spryker.atlassian.net/browse/CC-21838

Performed smoke b2c user control scenario:

1. Create a new Role / a new Group, assign to a user, check in Zed for the user
2. Create a new user + login in Zed
3. Delete / Deactivate a user
4. Edit a user

2022-10-30 21:08 UTC, AntonShopin requested changes
You need to cover the main idea of the user control feature - different roles. 
Please check this article: https://docs.spryker.com/docs/scos/user/back-office-user-guides/202204.0/users/best-practices-managing-users-and-their-permissions-with-roles-and-groups.html#creating-the-role-with-limited-access

With your tests, you need to create a new role with limited access and add a new group and user. Assign the user to it and log in with this user -> check that this user is not able to access something in Zed (pages or actions). 

To do this - you need to create a new keyword to manage different permissions in the role

2022-10-30 21:08 UTC, AntonShopin commented on tests/smoke/smoke_b2c.robot
> +    Zed: add new group:   Group${random}
see comment above from keywrods

2022-10-30 21:08 UTC, AntonShopin commented on tests/smoke/smoke_b2c.robot
> +    Zed: deactivate user
if you deactivate the user, how do you test that it's deactivated? Maybe it's better to try to log in with it and see that you can't ?

2022-11-03 08:23 UTC, khushal-rathore-metacube commented on tests/smoke/smoke_b2c.robot
> +User_control_functionality
Done

2022-11-03 08:29 UTC, khushal-rathore-metacube commented on resources/steps/zed_users_steps.robot
> +    Zed: submit the form
Done

2022-11-04 07:49 UTC, khushal-rathore-metacube commented on resources/pages/zed/zed_create_zed_user_page.robot
> +${zed_user_deactivate_button}    xpath=//form[contains(@name,'deactivate_user_form')]
Done

2022-11-04 07:50 UTC, khushal-rathore-metacube commented on resources/steps/zed_users_steps.robot
> +Zed: Add role name:
Done

2022-11-04 07:50 UTC, khushal-rathore-metacube commented on resources/steps/zed_users_steps.robot
> +Zed: add new group:
Done

2022-11-04 07:50 UTC, khushal-rathore-metacube commented on resources/steps/zed_users_steps.robot
> +     [Arguments]    ${Group_name}
Done

2022-11-04 07:50 UTC, khushal-rathore-metacube commented on tests/smoke/smoke_b2c.robot
> +    Zed: add a new user detatils:    abc${random}@gmail.com   change${random}   change${random}    khushal    singh
Done

2022-11-04 07:50 UTC, khushal-rathore-metacube commented on tests/smoke/smoke_b2c.robot
> +    Zed: add new group:   Group${random}
Done

2022-11-04 07:50 UTC, khushal-rathore-metacube commented on tests/smoke/smoke_b2c.robot
> +    Zed: deactivate user
Done

2022-11-16 19:30 UTC, AntonShopin commented on resources/steps/zed_users_steps.robot
> +    Click    ${zed_add_rule_button}
Why these steps are here, if you have another keyword for it? `Zed: apply restrictions for user role:`

2022-11-16 19:30 UTC, AntonShopin commented on resources/steps/zed_users_steps.robot
> +    [Arguments]    ${bundle_access}    ${controller_access}    ${action_access}    ${permission}
There are no conflicts? You have added new variables in the environment file - cool, I appreciate it. But in this keyword, you use exactly the same naming for arguments (which are also some kind of variables). Maybe it's better to rename argument so the are not mixed with variables from the env file?

2022-11-16 19:30 UTC, AntonShopin commented on resources/common/common_zed.robot
> +
are you sure that you have updated ALL tests and ALL keywords for ALL demoshops, where this keyword was used before? 
Previously it was required to provide only one argument. Now, with your changes, this keyword will run only if 2 arguments have been provided. 

For me it's a BC break, not allowed OR - you need to update ALL other places where this keyword is already used.

2022-11-16 19:30 UTC, AntonShopin commented on resources/steps/zed_users_steps.robot
> +    Zed: message should be shown:    success    Role "${name}" successfully added.
see my comment above about your changes to this keyword

2022-11-16 19:30 UTC, AntonShopin commented on resources/steps/zed_users_steps.robot
> +    [Arguments]    ${Group_name}    ${role_name}
Group_name should be in lower case

2022-11-16 19:30 UTC, AntonShopin commented on resources/steps/zed_users_steps.robot
> +    [Arguments]    ${Group_name}
Group_name should be in lower case

2022-11-16 19:30 UTC, AntonShopin commented on resources/steps/zed_users_steps.robot
> +    Zed: click Action Button in a table for row that contains:    abc${random}@gmail.com    Edit
from where did you get `abc${random}@gmail.com` ? Hardcode, no? Please refactor

2022-11-16 19:30 UTC, AntonShopin commented on tests/smoke/smoke_b2c.robot
> +Library    XML
what is this? From where and why do you need XML library?

2022-11-16 19:30 UTC, AntonShopin commented on tests/smoke/smoke_b2c.robot
> +    Zed: create new Zed user with the following data:    abc${random}@gmail.com   change${random}    Test    last    Root group    This user is an agent    en_US
Why first not to:
- Create new role
- Apply restrictions to this role
- Create new Group
- And only then create new user with this new group?

2022-11-21 09:31 UTC, khushal-rathore-metacube commented on resources/pages/zed/zed_user_role_page.robot
> +${zed_add_rule_button}    xpath=//form[@name='ruleset']//input[@class='btn btn-primary safe-submit']
Fixed

2022-11-21 09:33 UTC, khushal-rathore-metacube commented on resources/steps/zed_users_steps.robot
> +    Click    ${zed_add_rule_button}
fixed

2022-11-21 09:33 UTC, khushal-rathore-metacube commented on resources/steps/zed_users_steps.robot
> +    [Arguments]    ${bundle_access}    ${controller_access}    ${action_access}    ${permission}
fixed

2022-11-21 09:33 UTC, khushal-rathore-metacube commented on resources/common/common_zed.robot
> +
fixed

2022-11-21 09:33 UTC, khushal-rathore-metacube commented on resources/steps/zed_users_steps.robot
> +    Zed: message should be shown:    success    Role "${name}" successfully added.
fixed

2022-11-21 09:34 UTC, khushal-rathore-metacube commented on resources/steps/zed_users_steps.robot
> +    [Arguments]    ${Group_name}    ${role_name}
fixed

2022-11-21 09:34 UTC, khushal-rathore-metacube commented on resources/steps/zed_users_steps.robot
> +    [Arguments]    ${Group_name}
fixed

2022-11-21 09:49 UTC, khushal-rathore-metacube commented on resources/pages/zed/zed_catalog_attributes_page.robot
> +${attribute_access_denied_header}    xpath=//div[@class='wrapper wrapper-content']//h1
Fixed

2022-11-21 11:36 UTC, khushal-rathore-metacube commented on tests/smoke/smoke_b2c.robot
> +    Zed: create new Zed user with the following data:    abc${random}@gmail.com   change${random}    Test    last    Root group    This user is an agent    en_US
Fixed

2022-11-21 11:37 UTC, khushal-rathore-metacube commented on tests/smoke/smoke_b2c.robot
> +Library    XML
Fixed

2022-11-21 11:37 UTC, khushal-rathore-metacube commented on resources/steps/zed_users_steps.robot
> +    Zed: click Action Button in a table for row that contains:    abc${random}@gmail.com    Edit
Fixed

2022-11-22 17:07 UTC, AntonShopin commented on resources/steps/zed_users_steps.robot
> +    Click    ${zed_add_rule_button}
not fixed. My comment was to remove it from this keyword and you have just replaced inline action with a keyword. 

You need to design your test using different available keywords. Don't put everything under one keyword. 
Like, with keyword one you 'create a new role', using second keyword in your test - you specify restrictions

2022-11-22 17:07 UTC, AntonShopin commented on tests/smoke/smoke_b2c.robot
> +    Zed: apply restrictions for user role:    ${bundle_access}    ${controller_access}    ${action_access}    ${permission_deny}
Check my comment for `Zed: create new role with name:` keyword, where you already, for some reason, use `Zed: apply restrictions for user role:`
You see, we can create new roles with everything denied, with you hardcoded keyword in keyword all new roles will be created with 'all allowed', not good

2022-11-24 06:36 UTC, khushal-rathore-metacube commented on tests/smoke/smoke_b2c.robot
> +    Zed: apply restrictions for user role:    ${bundle_access}    ${controller_access}    ${action_access}    ${permission_deny}
Fixed. created two keywords `Zed: create new role with name:`  and `Zed: apply access permissions for user role:`

2022-11-24 06:59 UTC, khushal-rathore-metacube commented on resources/steps/zed_users_steps.robot
> +    Click    ${zed_add_rule_button}
Fixed

2024-01-18 13:04 UTC, closed without merging