smoke-b2b-Company-Account-in-Zed
spryker/robotframework-suite-tests pull request #369
Opened 2022-10-20 11:36 UTC by durgesh-verma-spryker

## PR Description
https://spryker.atlassian.net/browse/CC-21651

Company Account in Zed
- Smoke-b2b-Company-Account-in-Zed
- Create a new company in Zed, approve and activate
- Create a new BU to the new company
- Create a role for the new company
- Add new user to company, assign admin role
- Assign customer to the company (Customers → Customers→ Action "Attach to company")
- Assign the customer to another BU of the company (Company User → Action "Attach to BU")
- Add Company Business Unit Address

2022-10-30 20:28 UTC, AntonShopin requested changes
Be aware that you have commented all tests in the smoke file!

2022-10-30 20:28 UTC, AntonShopin commented on resources/steps/company_steps.robot
> +*** Variables ***
please don't describe variables in steps. Variables should be in pages. 
Check `resources/pages/zed/zed_create_company_business_unit_page.robot` `resources/pages/zed/zed_create_company_user_page.robot` and other pages ...

2022-10-30 20:28 UTC, AntonShopin commented on resources/steps/company_steps.robot
> +${zed_create_company_business_unit_dropdown}    xpath=(//b[@role="presentation"])[2]
looks like this locator needs to be updated. I can't get from where it's it and why you use role=presentation for 2 different locators, when one should be for company selector and the second for BU selector

2022-10-30 20:28 UTC, AntonShopin commented on resources/steps/company_steps.robot
> +${zed_save_button}    xpath=//input[@value="Save"]
What is wrong with the already existing keyword: `Zed: submit the form`? Why do we need this new locator?

2022-10-30 20:28 UTC, AntonShopin commented on resources/steps/company_steps.robot
> +   # wait until element is visible    ${zed_success_flash_message}
if this wait is not needed - remove, not comment

2022-10-30 20:28 UTC, AntonShopin commented on resources/steps/company_steps.robot
> +Zed: Business Unit Address
Your keyword sounds like a statement, rename it to have a command. 

Keyword should support arguments

2022-10-30 20:28 UTC, AntonShopin commented on resources/steps/company_steps.robot
> +   Type Text    id=company_unit_address_address1    address1${random}
Why do you hardcode locators? They should be moved to pages

2022-10-30 20:28 UTC, AntonShopin commented on resources/steps/company_steps.robot
> +Zed: Delete Company Business Unit:
Please rename to: `Zed: delete company business unit:`

2022-10-30 20:28 UTC, AntonShopin commented on tests/smoke/smoke_b2b.robot
> +    Zed: Business Unit Address
What about this assertion? 
`Login in Yves as the new customer of the company → Go to company account details, check all details and users in Yves.`
It's the final step from https://spryker.atlassian.net/wiki/spaces/PS/pages/846791112/B2B+Demoshop+Smoke+Test+Checklist#B2BDemoshopSmokeTestChecklist-CompanyAccountinZed
If you don't know how to get the email - try a workaround with DataBase

2022-11-03 13:59 UTC, durgesh-verma-spryker commented on resources/steps/company_steps.robot
> +*** Variables ***
Fixed

2022-11-03 14:00 UTC, durgesh-verma-spryker commented on resources/steps/company_steps.robot
> +${zed_create_company_business_unit_dropdown}    xpath=(//b[@role="presentation"])[2]
Fixed

2022-11-03 14:00 UTC, durgesh-verma-spryker commented on resources/steps/company_steps.robot
> +Zed: Business Unit Address
Fixed

2022-11-03 14:01 UTC, durgesh-verma-spryker commented on resources/steps/company_steps.robot
> +Zed: Delete Company Business Unit:
Fixed

2022-11-03 14:01 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +    Zed: Business Unit Address
Fixed

2022-11-16 18:47 UTC, AntonShopin commented on resources/common/common_yves.robot
> +    [Return]    ${response_body}
Why API keywords are in UI keywords? If you need yo use API requests -> just add common_api in files (where it's needed) as a Resource

2022-11-16 18:47 UTC, AntonShopin commented on resources/common/common_yves.robot
> +    [Return]    ${response_body}
Why API keywords are in UI keywords? If you need yo use API requests -> just add common_api in files (where it's needed) as a Resource

2022-11-16 18:47 UTC, AntonShopin commented on resources/steps/company_steps.robot
> +   [Arguments]    ${company}    ${country}    ${city}    ${ziprode}    ${street}
typo in `ziprode`

2022-11-16 18:47 UTC, AntonShopin commented on resources/steps/company_steps.robot
> +   Zed: submit the form
you expect arguments but they are not used inside the keyword. You hardcoded values

2022-11-16 18:47 UTC, AntonShopin commented on resources/steps/company_steps.robot
> +    [Arguments]    ${email}
please add a second argument, for the password, it should not be hardcoded. You can specify the default value, but please don't hardcode. Example:
`Arguments]    ${email}    ${password}=${yves_user_password}` and check it PATCH request change ${yves_user_password} on ${password}

2022-11-16 18:47 UTC, AntonShopin commented on resources/steps/company_steps.robot
> +Yves: check details of users:
please rename it and refactor. 
It should be self-explaining. 
Also, what does it check? Looks like the table with Users contains some specific name1 and name2. 
What are `name1 and name2`?

What if the table will contain 100 users, where name1 and name2 can be duplicated for different users. 

Also, why so bad locators? `//strong[normalize-space()='${name1}'] ` Just for example: `//div[@data-qa='component user-table']//table//td[@data-content='Name']/*[contains(text(),'${name1}')]`

2022-11-16 18:47 UTC, AntonShopin commented on tests/smoke/smoke_b2b.robot
> +    Zed: create new Company with provided name:    ${random}
`${random}` is a company name, are you sure?

2022-11-16 18:47 UTC, AntonShopin commented on tests/smoke/smoke_b2b.robot
> +    Zed: create new Company Business Unit with provided name and company:    Meta12BU    meta
always add random to have unique companies, business units and so on. Maybe `Meta12BU${random}`?

Also, how does it work? First, You create a company with the name `${random}`, then you create a BU for a company with the name `meta`? How is it possible 

**Please answer in this comment on the following question: Do you run your tests before creating a PR?**

2022-11-16 18:47 UTC, AntonShopin commented on tests/smoke/smoke_b2b.robot
> +    Zed: create new Company Role with provided permissions:    meta    Meta12role    true
Where are the permissions? You have no specified them

2022-11-16 18:47 UTC, AntonShopin commented on tests/smoke/smoke_b2b.robot
> +    Zed: Create new Company User with provided email/company/business unit and role(s):    abc${random}@mail.com    spryker    spryker    ADMINISTRATOR
what? Previously, you have created a new Company, then you have create a new BU, and now you DON'T use them. Then why you have created a new company and BU and role of you don't use them?

2022-11-16 18:47 UTC, AntonShopin commented on tests/smoke/smoke_b2b.robot
> +    ...    AND    Zed: delete company business unit:    ${random}
I will not review this part until the previous comments are not fixed. No sense. 
Just a note, this test was 90% already developed and exists for > a year. Only part with setting a password for a newly created customer was missing. Read it, find it in the code and compare with yours

```UJ:Managing_B2B_Copmany_Account_in_Zed_Part_1
    [Documentation]    This user journey is to check possibility to Create Company, Business unit and initial Admin user with Permissions for Managing User in Zed
    Zed: Login on Zed with Provided Credentials:    ${admin_email}  ${default_password}
    Zed: create new Company with provided name:    Robot+${random}
    Zed: click Action Button in a table for row that contains:    Robot+${random}    Approve
    Zed: click Action Button in a table for row that contains:    Robot+${random}    Activate
    Zed: create new Company Role with provided permissions:    Robot+${random}    Test Robot Role+${random}    false    Add company users    Invite users    Enable / Disable company users    See Company Menu    Add item to cart    Change item in cart    Remove item from cart    Place Order    Alter Cart Up To Amount
    Zed: create new Company Role with provided permissions:    Trial    Existing Role+${random}    false    Add company users    Invite users    Enable / Disable company users    See Company Menu    Add item to cart    Change item in cart    Remove item from cart    Place Order    Alter Cart Up To Amount
    Zed: create new Company Business Unit with provided name and company:    Test Robot BU+${random}    Robot+${random}
    Zed: Create new Company User with provided email/company/business unit and role(s):    ${test_customer_email}    Robot+${random}    Test Robot BU+${random}    (id: ${newly_created_business_unit_id})    Test Robot Role+${random}
    Yves: Login on Yves with Provided Credentials:     ${test_customer_email}
    Yves: company menu 'should' be available for logged in user   
    Zed: click button in Header:  button_name```

2022-11-22 12:05 UTC, durgesh-verma-spryker commented on resources/common/common_yves.robot
> +    [Return]    ${response_body}
Done, keeping as it is , as updating it leads to conflict in setup

2022-11-22 12:05 UTC, durgesh-verma-spryker commented on resources/common/common_yves.robot
> +    [Return]    ${response_body}
Done, keeping as it is , as updating it leads to conflict in setup

2022-11-22 12:23 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +    Zed: Create new Company User with provided email/company/business unit and role(s):    abc${random}@mail.com    spryker    spryker    ADMINISTRATOR
Fixed

2022-11-22 12:23 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +    Zed: create new Company Role with provided permissions:    meta    Meta12role    true
Fixed

2022-11-22 12:23 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +    Zed: create new Company with provided name:    ${random}
Fixed, as per your suggestion

2022-11-22 12:23 UTC, durgesh-verma-spryker commented on resources/steps/company_steps.robot
> +Yves: check details of users:
Fixed

2022-11-22 12:23 UTC, durgesh-verma-spryker commented on resources/steps/company_steps.robot
> +    [Arguments]    ${email}
fixed

2022-11-22 12:23 UTC, durgesh-verma-spryker commented on resources/steps/company_steps.robot
> +   Zed: submit the form
Fixed

2022-11-22 12:23 UTC, durgesh-verma-spryker commented on resources/steps/company_steps.robot
> +   [Arguments]    ${company}    ${country}    ${city}    ${ziprode}    ${street}
Fixed

2022-11-22 12:23 UTC, durgesh-verma-spryker commented on resources/common/common_yves.robot
> +    [Return]    ${response_body}
Done, keeping as it is , as updating it leads to conflict in setup

2022-11-22 12:23 UTC, durgesh-verma-spryker commented on resources/common/common_yves.robot
> +    [Return]    ${response_body}
Done, keeping as it is , as updating it leads to conflict in setup

2022-11-22 12:24 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +    ...    AND    Zed: delete company business unit:    ${random}
All the previous comments are fixed

2022-11-22 16:40 UTC, AntonShopin commented on resources/common/common_yves.robot
> +    [Return]    ${response_body}
What is the reason why you still keep it in common_yves?

2022-11-22 16:40 UTC, AntonShopin commented on resources/common/common_yves.robot
> +    [Return]    ${response_body}
What is the reason why you still keep it in common_yves?

2022-11-22 17:22 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +    [Teardown]    Run Keywords    Zed: delete company user xxx withing xxx company business unit:    ${random}    spryker
Fixed, Mistakenly Forgot replace with '${test_customer_email}' ,'Test Robot BU+${random}'

2022-11-22 17:28 UTC, durgesh-verma-spryker commented on resources/common/common_yves.robot
> +    [Return]    ${response_body}
![image](https://user-images.githubusercontent.com/114677860/203376309-9865cb3a-673e-46cf-b96d-d9f27739c1fb.png)

when I add a common_api file as a resource and remove these keywords from common_yves. I get conflict in suite setup and I am not able to execute tests. That's the reason I did not remove it.

2024-01-18 13:04 UTC, closed without merging