smoke b2c payment method update
spryker/robotframework-suite-tests pull request #370
Opened 2022-10-21 08:44 UTC by khushal-rathore-metacube

https://spryker.atlassian.net/browse/CC-21836

Performed smoke b2c payment method update

- Update payment method → Check in Yves
- Deactivate payment method → Check in Yves
- Unset payment method for store → Check in Yves

2022-10-30 19:56 UTC, AntonShopin requested changes

2022-10-30 19:56 UTC, AntonShopin commented on resources/steps/pdp_steps.robot
> +Yves: add a concrete product to cart
why do we need this new keyword? 
what is wrong with `Yves: add product to the shopping cart`?

2022-10-30 19:56 UTC, AntonShopin commented on tests/smoke/smoke_b2c.robot
> +    Page Should Not Contain Element    ${checkout_payment_invoice}
Please don't use 'default' robot keywords in tests. Create a new keyword (if it doesn't exist) to check if the payment method is displayed or not and the expected condition for it

2022-10-30 19:56 UTC, AntonShopin commented on tests/smoke/smoke_b2c.robot
> +Payment_method_update
you need to change the order of your steps. 

1. Without any changes in Zed -> check that the Invoice payment method is displayed during the checkout 
2. Edit in Zed (deactivate)
3. Return to Yves checkout and see that now it's not displayed 
4. Activate it back in Zed so we return to the initial state

2022-11-03 06:30 UTC, khushal-rathore-metacube commented on tests/smoke/smoke_b2c.robot
> +Payment_method_update
Done

2022-11-03 06:30 UTC, khushal-rathore-metacube commented on tests/smoke/smoke_b2c.robot
> +    Page Should Not Contain Element    ${checkout_payment_invoice}
Done

2022-11-03 06:36 UTC, khushal-rathore-metacube commented on resources/steps/pdp_steps.robot
> +Yves: add a concrete product to cart
Done

2022-11-16 17:47 UTC, AntonShopin commented on resources/steps/checkout_steps.robot
> +    END
1. Please rename it. Maybe: `Yves: check that the payment method is/not present in the checkout process:` ?
2. Avoid using Upper case in boolean values. it should be true or false (lower case)

2022-11-17 09:47 UTC, khushal-rathore-metacube commented on resources/steps/checkout_steps.robot
> +    END
fixed

2022-11-17 10:44 UTC, AntonShopin approved these changes

2022-11-22 15:56 UTC, AntonShopin approved these changes

2022-11-23 07:56 UTC, merged