b2b-smoke-test-back-office-translation
spryker/robotframework-suite-tests pull request #371
Opened 2022-10-21 12:08 UTC by durgesh-verma-spryker

## PR Description
https://spryker.atlassian.net/browse/CC-21651

Back-office translation
- Create a user in Zed with de_DE value in Locale, login as the user in Zed and check that translation is in DE (where implemented)
- Create a user in Zed with en_US value in Locale, login as the user in Zed and check that translation is in EN
- Edit a user in Zed with en_US value in Locale to de_DE, login as the user in Zed and check that translation is in DE (where implemented)

2022-10-30 19:45 UTC, AntonShopin requested changes

2022-10-30 19:45 UTC, AntonShopin commented on resources/steps/zed_users_steps.robot
> +*** Variables ***
please don't mix variables with steps. Variables should be in 'pages', keywords in 'steps' . 
Also, looks like almost all these locators are already present in `resources/pages/zed/zed_create_zed_user_page.robot`

2022-10-30 19:45 UTC, AntonShopin commented on resources/steps/zed_users_steps.robot
> +   END
Looks like we already have a keyword for this. Please check `Zed: create new Zed user with the following data:`

2022-10-30 19:45 UTC, AntonShopin commented on resources/steps/zed_users_steps.robot
> +Zed: validation of translation:
please rename it. It should sound like a command, f.e. `Zed: validate that the back office content is in: ${variable}`

2022-10-30 19:45 UTC, AntonShopin commented on resources/steps/zed_users_steps.robot
> +   [Arguments]    ${type}
not type but locale

2022-10-30 19:45 UTC, AntonShopin commented on resources/steps/zed_users_steps.robot
> +   END
do we need to hardcode here this locator? 
Maybe it would be better to get the text from the already existing 'Log out' button. Locator for it is `${zed_log_out_button}` and move its' translation into environment file? 
I don't like that we hardcode `Willkommen abcd wxyz [docker.dev]`

2022-10-30 19:45 UTC, AntonShopin commented on tests/smoke/smoke_b2b.robot
> +   Zed: Add new users in with following email:
please check my comment about this new keyword.  
Your new keyword looks better as it uses table format, but I don't like to have 2 keywords that do the same. 

You need to use the old keyword or refactor the old one to support the table format and replace it in ALL tests for all 4 demoshops, up to you

2022-10-30 19:45 UTC, AntonShopin commented on tests/smoke/smoke_b2b.robot
> +   Zed: select interface language:    de_DE
never change the state of the default admin user. With your test, you have changed the local for admin@spryker.com to DE and left it. Now the whole admin interface is now in DE. All other tests will fail + if we run it on staging and I or you would like to log in under admin user - we'll see everything in DE and finish your test using it?

You have created a new user with your test with EN local. Why not to edit it to have DE locale?

2022-11-02 15:09 UTC, durgesh-verma-spryker commented on resources/steps/zed_users_steps.robot
> +*** Variables ***
Fixed

2022-11-02 15:09 UTC, durgesh-verma-spryker commented on resources/steps/zed_users_steps.robot
> +   END
Done

2022-11-02 15:09 UTC, durgesh-verma-spryker commented on resources/steps/zed_users_steps.robot
> +Zed: validation of translation:
Fixed

2022-11-02 15:09 UTC, durgesh-verma-spryker commented on resources/steps/zed_users_steps.robot
> +   [Arguments]    ${type}
Fixed

2022-11-02 15:10 UTC, durgesh-verma-spryker commented on resources/steps/zed_users_steps.robot
> +   END
Fixed

2022-11-02 15:10 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +   Zed: Add new users in with following email:
Fixed

2022-11-02 15:13 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +   Zed: select interface language:    de_DE
we did not made any changes for admin@spryker.com in DE, we have already created a new user for our tests and changed the interface language for that particular user

2022-11-16 17:18 UTC, AntonShopin commented on resources/pages/zed/zed_create_zed_user_page.robot
> +${agent_checkbox_locator}    xpath=//input[@name="user[is_agent]"]
what is it for? I don't see that it's used somewhere

2022-11-21 06:46 UTC, durgesh-verma-spryker commented on resources/pages/zed/zed_create_zed_user_page.robot
> +${agent_checkbox_locator}    xpath=//input[@name="user[is_agent]"]
Removed

2022-11-21 06:46 UTC, durgesh-verma-spryker commented on resources/pages/zed/zed_reclaimation_page.robot
> +${create_reclamation_button_locator}    xpath=//input[@type="submit"]
Removed

2022-11-21 06:46 UTC, durgesh-verma-spryker commented on resources/pages/zed/zed_create_zed_user_page.robot
> +${root_group_checkbox_locator}    xpath=//input[@name="user[group][]"]
Fixed

2022-11-22 15:51 UTC, AntonShopin submitted a review, later dismissed

2024-01-18 13:04 UTC, closed without merging