smoke-b2c- agent assist
spryker/robotframework-suite-tests pull request #372
Opened 2022-10-26 11:56 UTC by khushal-rathore-metacube

https://spryker.atlassian.net/browse/CC-21836

- Impersonate / unimpersonate as a customer
- Place an order for a customer

2022-10-30 19:17 UTC, AntonShopin requested changes

2022-10-30 19:17 UTC, AntonShopin commented on resources/steps/agent_assist_steps.robot
> +Yves: End customer assistance
Remane to `Yves: end customer assistance`

2022-10-30 19:17 UTC, AntonShopin commented on tests/smoke/smoke_b2c.robot
> +     Yves: click on the 'Checkout' button in the shopping cart
please fix the alignment

2022-10-30 19:17 UTC, AntonShopin commented on tests/smoke/smoke_b2c.robot
> +    Yves: End customer assistance
You also need to test that in Zed or Yves the new order has been created by the customer. 
So we log in under Bill using the Agent assist feature and place an order. In the end, we need to check that Bill has a new order

2022-11-01 03:08 UTC, khushal-rathore-metacube commented on resources/steps/agent_assist_steps.robot
> +Yves: End customer assistance
Done

2022-11-01 03:08 UTC, khushal-rathore-metacube commented on tests/smoke/smoke_b2c.robot
> +     Yves: click on the 'Checkout' button in the shopping cart
Done

2022-11-01 12:47 UTC, AntonShopin reviewed
Good job. 2 minor changes and we are done here

2022-11-01 12:47 UTC, AntonShopin commented on resources/steps/agent_assist_steps.robot
> +Yves: as an agent login under the customer:
thank you for formatting it in the right way. 
Could you please replace in all other tests/files this keyword so we don't have a situation, when part of the tests use `Yves: As an Agent login under the customer:` and only 2 `Yves: as an agent login under the customer:`
It should be really simple and quick with replace function in IDE

2022-11-01 14:51 UTC, khushal-rathore-metacube commented on tests/smoke/smoke_b2c.robot
> +    Yves: perform search by customer:    ${yves_second_user_first_name}
Done

2022-11-01 14:51 UTC, khushal-rathore-metacube commented on resources/steps/agent_assist_steps.robot
> +Yves: as an agent login under the customer:
Done

2022-11-02 09:14 UTC, AntonShopin approved these changes

2022-11-02 14:05 UTC, merged