b2b-smoke-delivery-methods
spryker/robotframework-suite-tests pull request #373
Opened 2022-10-27 11:10 UTC by durgesh-verma-spryker

## PR Description
https://spryker.atlassian.net/browse/CC-21651

Delivery methods

- Check the list of delivery methods → Check in Zed
- Create a new carrier company → Check in Zed and Yves
- Create a new delivery method → Check in Zed and Yves
- View the delivery method → Check in Zed
- Edit the delivery method → Check in Zed and Yves
- Delete the delivery method → Check in Zed and Yves
- Deactivate delivery method → Check in Yves
- Unset delivery method for store → Check in Yves

2022-10-30 19:00 UTC, AntonShopin requested changes

2022-11-08 09:42 UTC, durgesh-verma-spryker commented on resources/steps/zed_delivery_methods_steps.robot
> +*** Variables ***
Fixed

2022-11-09 10:18 UTC, durgesh-verma-spryker commented on resources/steps/zed_delivery_methods_steps.robot
> +*** Variables ***
Fixed

2022-11-09 10:18 UTC, durgesh-verma-spryker commented on resources/steps/zed_delivery_methods_steps.robot
> +${create_company_button_locator}    xpath=//a[contains(@href,"/shipment-gui/create-carrier/index")]
Fixed

2022-11-09 10:18 UTC, durgesh-verma-spryker commented on resources/steps/zed_delivery_methods_steps.robot
> +${confirm_delete_button_locator}    id=shipment_method_delete_form_submit
Fixed

2022-11-09 10:18 UTC, durgesh-verma-spryker commented on resources/steps/zed_delivery_methods_steps.robot
> +${name_locator}    id=shipment_method_name
Fixed

2022-11-09 10:18 UTC, durgesh-verma-spryker commented on resources/steps/zed_delivery_methods_steps.robot
> +    Type Text    id=shipment_carrier_name    ${carrier_name}
Fixed

2022-11-09 10:18 UTC, durgesh-verma-spryker commented on resources/steps/zed_delivery_methods_steps.robot
> +Zed: Price & Tax:
fixed

2022-11-09 10:18 UTC, durgesh-verma-spryker commented on resources/steps/zed_delivery_methods_steps.robot
> +Zed: Store Relation checkbox
Fixed

2022-11-09 10:18 UTC, durgesh-verma-spryker commented on resources/steps/zed_delivery_methods_steps.robot
> +Zed: Store Relation uncheckbox
Fixed

2022-11-09 10:18 UTC, durgesh-verma-spryker commented on resources/steps/zed_delivery_methods_steps.robot
> +    Page Should Contain Element    xpath=//span[contains(text(),'${carrier_name}')]
Fixed

2022-11-09 10:18 UTC, durgesh-verma-spryker commented on resources/steps/zed_delivery_methods_steps.robot
> +Yves: Check delivery method:
Fixed

2022-11-09 10:18 UTC, durgesh-verma-spryker commented on resources/steps/zed_delivery_methods_steps.robot
> +Zed: unset delivery method for store:
Fixed

2022-11-09 10:19 UTC, durgesh-verma-spryker commented on resources/steps/zed_delivery_methods_steps.robot
> +Zed: edit delivery method:
Fixed

2022-11-09 10:19 UTC, durgesh-verma-spryker commented on resources/steps/zed_delivery_methods_steps.robot
> +    Page Should Contain Element    xpath=//span[@class="radio__label radio__label--expand label "]//span[contains(text(),'${delivery_method_name}')]
Fixed

2022-11-09 10:19 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +delivery methods
Fixed

2022-11-09 10:19 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +    Zed: go to second navigation item level:    Administration    Delivery Methods
Fixed

2022-11-09 10:19 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +    ...    || gross_price_de_chf | gross_price_de_euro | gross_price_at_chf | gross_price_at_euro | net_price_de_chf  | net_price_de_euro | net_price_at_chf | net_price_at_euro  |  tax_set  ||
Fixed

2022-11-09 10:19 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +    Zed: click Action Button in a table for row that contains:    Name${random}    View
Fixed

2022-11-09 10:19 UTC, durgesh-verma-spryker commented on resources/steps/zed_delivery_methods_steps.robot
> +Yves: Check carrier company:
Fixed

2022-11-09 10:19 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +    Yves: Check delivery method:    Name${random}
Fixed

2022-11-09 10:26 UTC, durgesh-verma-spryker commented on resources/steps/zed_delivery_methods_steps.robot
> +    Page Should Not Contain Element    xpath=//span[@class="radio__label radio__label--expand label "]//span[contains(text(),'${delivery_method_name}')]
Fixed

2022-11-16 16:56 UTC, AntonShopin commented on resources/pages/zed/zed_delivery_method_pages.robot
> +*** Variables ***
please rename the file. 'pages' should not be in plural

2022-11-16 16:56 UTC, AntonShopin commented on resources/pages/zed/zed_delivery_method_pages.robot
> +${tax_set_locator}    id=shipment_method_fkTaxSet
all these locators should be renamed. During my previous review, I've written that "Locator name should contain such details, like 'confirm_delete_shipment_method'"
Now I see `${de_locator}`, de locator of what? locator name should be self-explaining.

2022-11-16 16:56 UTC, AntonShopin commented on resources/pages/zed/zed_delivery_method_pages.robot
> +${price_plugin_dropdown_locator}    id=shipment_method_pricePlugin
please rename locators. Names should be self-explaining

2022-11-16 16:56 UTC, AntonShopin commented on resources/steps/zed_delivery_methods_steps.robot
> +
please fix the formatting: add br after resources and remove be after keywords

2022-11-16 16:56 UTC, AntonShopin commented on resources/steps/zed_delivery_methods_steps.robot
> +Zed: create delivery method:
please add br between keywords

2022-11-16 16:56 UTC, AntonShopin commented on resources/steps/zed_delivery_methods_steps.robot
> +        IF    '${key}'=='Carrier' and '${value}' != '${EMPTY}'    Select From List By Text    ${carrier_dropdown_locator}    ${value}
nice, just, please change the expected keys from upper case to lower case. Same in test

2022-11-16 16:56 UTC, AntonShopin commented on resources/steps/zed_delivery_methods_steps.robot
> +    Zed: Check checkbox by Label:     Is active
1. These 2 actions look like duplicates of each other, no? 
2. Why not to combine this keyword with `Zed: add price & tax of delivery method and store relation:`?

2022-11-16 16:56 UTC, AntonShopin commented on resources/steps/zed_delivery_methods_steps.robot
> +Zed: checkbox/uncheckbox store relation in delivery method:
Please rename it. 'uncheckbox' - such a word doesn't exist

2022-11-16 16:56 UTC, AntonShopin commented on resources/steps/zed_delivery_methods_steps.robot
> +Yves: check availability carrier company and delivery method:
1. Please rename it, it sounds confusing. Maybe: `Yves: check that the delivery method of a carrier is/not available:`
2. Why Yves keyword is in 'zed_delivery_methods_steps.robot' file? We have 'checkout_steps.robot', maybe it's better to move it there?

2022-11-16 16:56 UTC, AntonShopin commented on resources/steps/zed_delivery_methods_steps.robot
> +    Zed: submit the form
Please refactor. Your keyword should not 'Deactivate' the method AND remove store relation. 
What if I need just to deactivate it and check that it's not available on Yves? -> this method doesn't fit as it will remove store relation as well. What if I need to keep the method active but remove it only from one store -> this method doesn't fit as it will deactivate the method as well.

2022-11-16 16:56 UTC, AntonShopin commented on resources/steps/zed_delivery_methods_steps.robot
> +Zed: edit delivery method:
not fixed. All means all, including prices and store relations.

2022-11-16 16:56 UTC, AntonShopin commented on resources/steps/zed_delivery_methods_steps.robot
> +        IF    '${key}'=='Carrier' and '${value}' != '${EMPTY}'    Select From List By Text    ${carrier_dropdown_locator}    ${value}
please use lower case for keys

2022-11-16 16:56 UTC, AntonShopin commented on resources/steps/zed_delivery_methods_steps.robot
> +    Page Should Not Contain Element    xpath=//span[contains(@class,"radio__label")]//span[contains(text(),'${delivery_method_name}')]
Why do you need this one? You've already created `Yves: check availability carrier company and delivery method:`, no?

2022-11-16 16:56 UTC, AntonShopin commented on tests/smoke/smoke_b2b.robot
> +    ...    || gross_price_de_chf | gross_price_de_euro | gross_price_at_chf | gross_price_at_euro | net_price_de_chf  | net_price_de_euro | net_price_at_chf | net_price_at_euro  |  tax_set  ||
not fixed, you have not combined them into one

2022-11-16 17:06 UTC, AntonShopin commented on tests/smoke/smoke_b2b.robot
> +    Yves: create new 'Shopping Cart' with name:    carting+${random}
please create new carts, shopping lists, customers, etc with unique names. The easiest way is to add a feature name to it, like `deliveryMethodCart${random}.` I'm almost sure that in other PRs there is a step where you create the cart with exactly the same name

2022-11-16 17:06 UTC, AntonShopin commented on tests/smoke/smoke_b2b.robot
> +    Yves: check availability carrier company and delivery method:    new_MethodName${random}    MethodName${random}    true
How it can work? Do you run your tests? 
You create a new method -> you check that it's available on the checkout. 

Then you Edit it -> you check that the updated method is available on the checkout and you check THAT OLD method name is still available on the checkout. How is that possible?

2022-11-16 17:06 UTC, AntonShopin commented on tests/smoke/smoke_b2b.robot
> +    Yves: verifying deactivated/unset delivery method not present on page:    new_MethodName${random}
your PR contains the following description: 

- Delete the delivery method → Check in Zed and Yves
- Deactivate delivery method → Check in Yves
- Unset delivery method for store → Check in Yves

Where are these steps and assertions, one by one?

2022-11-26 05:55 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +    Yves: verifying deactivated/unset delivery method not present on page:    new_MethodName${random}
Fixed, added steps and assertion

2022-11-26 05:56 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +    Yves: check availability carrier company and delivery method:    new_MethodName${random}    MethodName${random}    true
Fixed

2022-11-26 05:56 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +    Yves: create new 'Shopping Cart' with name:    carting+${random}
Fixed

2022-11-26 05:56 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +    Yves: check availability carrier company and delivery method:    company${random}    MethodName${random}    true
Fixed, added price assertion also.

2022-11-26 05:56 UTC, durgesh-verma-spryker commented on resources/steps/zed_delivery_methods_steps.robot
> +    Page Should Not Contain Element    xpath=//span[contains(@class,"radio__label")]//span[contains(text(),'${delivery_method_name}')]
Fixed

2022-11-26 05:57 UTC, durgesh-verma-spryker commented on resources/steps/zed_delivery_methods_steps.robot
> +        IF    '${key}'=='Carrier' and '${value}' != '${EMPTY}'    Select From List By Text    ${carrier_dropdown_locator}    ${value}
Fixed

2022-11-26 05:57 UTC, durgesh-verma-spryker commented on resources/steps/zed_delivery_methods_steps.robot
> +    Zed: submit the form
Fixed, added separate keywords.

2022-11-26 05:57 UTC, durgesh-verma-spryker commented on resources/steps/zed_delivery_methods_steps.robot
> +Yves: check availability carrier company and delivery method:
Fixed

2022-11-26 05:58 UTC, durgesh-verma-spryker commented on resources/steps/zed_delivery_methods_steps.robot
> +Zed: checkbox/uncheckbox store relation in delivery method:
Fixed

2022-11-26 05:58 UTC, durgesh-verma-spryker commented on resources/steps/zed_delivery_methods_steps.robot
> +    Zed: Check checkbox by Label:     Is active
Fixed

2022-11-26 05:58 UTC, durgesh-verma-spryker commented on resources/steps/zed_delivery_methods_steps.robot
> +        IF    '${key}'=='Carrier' and '${value}' != '${EMPTY}'    Select From List By Text    ${carrier_dropdown_locator}    ${value}
Fixed

2022-11-26 05:58 UTC, durgesh-verma-spryker commented on resources/steps/zed_delivery_methods_steps.robot
> +Zed: create delivery method:
Fixed

2022-11-26 05:58 UTC, durgesh-verma-spryker commented on resources/steps/zed_delivery_methods_steps.robot
> +
Fixed

2022-11-26 05:58 UTC, durgesh-verma-spryker commented on resources/pages/zed/zed_delivery_method_pages.robot
> +${price_plugin_dropdown_locator}    id=shipment_method_pricePlugin
Fixed

2022-11-26 05:58 UTC, durgesh-verma-spryker commented on resources/pages/zed/zed_delivery_method_pages.robot
> +${tax_set_locator}    id=shipment_method_fkTaxSet
Fixed

2022-11-26 05:59 UTC, durgesh-verma-spryker commented on resources/pages/zed/zed_delivery_method_pages.robot
> +*** Variables ***
Fixed

2022-11-26 05:59 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +    ...    || gross_price_de_chf | gross_price_de_euro | gross_price_at_chf | gross_price_at_euro | net_price_de_chf  | net_price_de_euro | net_price_at_chf | net_price_at_euro  |  tax_set  ||
Fixed, combined them into one

2022-11-26 05:59 UTC, durgesh-verma-spryker commented on resources/steps/zed_delivery_methods_steps.robot
> +Zed: edit delivery method:
Fixed, all combined into one

2024-01-18 13:04 UTC, closed without merging