B2b smoke test reclaimation
spryker/robotframework-suite-tests pull request #374
Opened 2022-10-28 08:10 UTC by durgesh-verma-spryker

## PR Description
https://spryker.atlassian.net/browse/CC-21651

Reclamation
-  Create a Reclamation for some products of the order and process their statuses in the Reclamation details. Close reclamation

2022-10-30 18:12 UTC, AntonShopin requested changes

2022-10-30 18:12 UTC, AntonShopin commented on resources/steps/reclaimation_steps.robot
> +*** Variables ***
don't mix variables with keywords. 
For variables create a separate file to describe this page (locators). Page Object pattern. 
Actions (keywords) should stay in '_steps' file

2022-10-30 18:12 UTC, AntonShopin commented on resources/steps/reclaimation_steps.robot
> +zed: create reclaimation
'zed' should start from the upper case and you have a typo. "Zed: create reclamation"

This keyword is not 'smart' enough:
* with this keyword it should be possible to create a reclamation for all items or for some specific ones. Please refactor

2022-10-30 18:12 UTC, AntonShopin commented on resources/steps/reclaimation_steps.robot
> +Zed: select latest Reclamation
well, I don't agree with this one, you just click on the first column to sort, but what if the table is already sorted by the first column? You need to check if it 'ascending' and only then click to sort to have 'descending'. If it's already 'descending' - do not click

2022-10-30 18:12 UTC, AntonShopin commented on tests/smoke/smoke_b2b.robot
> +Reclaimation
Your tests should cover the following: 
* create reclamation for part of the order items, not the whole order
* view the details of the Reclamation and check that only selected items are inside this Reclamation 
* Close the reclamation and check that the state of the Reclamation is now 'closed'

2022-11-02 15:07 UTC, durgesh-verma-spryker commented on resources/steps/reclaimation_steps.robot
> +*** Variables ***
Done

2022-11-02 15:07 UTC, durgesh-verma-spryker commented on resources/steps/reclaimation_steps.robot
> +zed: create reclaimation
Fixed

2022-11-02 15:08 UTC, durgesh-verma-spryker commented on resources/steps/reclaimation_steps.robot
> +Zed: select latest Reclamation
Fixed

2022-11-07 17:45 UTC, durgesh-verma-spryker commented on resources/steps/reclaimation_steps.robot
> +*** Variables ***
Fixed

2022-11-07 17:45 UTC, durgesh-verma-spryker commented on resources/steps/reclaimation_steps.robot
> +zed: create reclaimation
Fixed

2022-11-07 17:45 UTC, durgesh-verma-spryker commented on resources/steps/reclaimation_steps.robot
> +Zed: select latest Reclamation
Fixed

2022-11-07 17:45 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +Reclaimation
Fixed

2022-11-16 16:02 UTC, AntonShopin commented on resources/steps/reclaimation_steps.robot
> +   [Arguments]    ${sku}    ${reclaim}=1
1. This keyword should accept multiple SKUs, not just one
2. What is the role of `${reclaim}=1`, sorry, I didn't get the usage

2022-11-16 16:02 UTC, AntonShopin commented on resources/steps/reclaimation_steps.robot
> +      ${elementSelector}=    Set Variable    xpath=//table[@data-qa='order-item-list'][${reclaim}]/tbody//td//div[@class='sku'][contains(text(),'${sku}')]/ancestor::tr/td/input[@type="checkbox"]
Both variables are exactly the same. Why did you put `IF` here?

2022-11-16 16:06 UTC, AntonShopin commented on resources/steps/reclaimation_steps.robot
> +Zed: check details of latest created reclaimation:
1. please rename it. Looks like this keyword supposes to check that the latest reclamation contains some SKUs. From the current name, it's not clear
2. please refactor so it accepts multiple SKUs

2022-11-16 16:15 UTC, AntonShopin commented on resources/steps/reclaimation_steps.robot
> +Zed: check state of latest reclaimation:
1. Please rename it so it's clear what argument I should pass
2. This keyword doesn't work as your locator for the state is hardcoded for 'Closed' state. If the Reclamation is 'Open' - you locator shows 0 results

2022-11-24 19:07 UTC, durgesh-verma-spryker commented on resources/pages/zed/zed_reclaimation_page.robot
> +${state_reclaimation_locator}    (//span[contains(@class,"label-danger")])[1]
Fixed

2022-11-24 19:08 UTC, durgesh-verma-spryker commented on resources/steps/reclaimation_steps.robot
> +Zed: check checkbox of reclaimation of whole order
Fixed

2022-11-24 19:09 UTC, durgesh-verma-spryker commented on resources/steps/reclaimation_steps.robot
> +   ${second}    Get Text    xpath=(//tbody/tr/td[@class="column-spy_sales_reclamation.id_sales_reclamation sorting_1"])[2]
Fixed, as per your suggestion

2022-11-24 19:12 UTC, durgesh-verma-spryker commented on resources/steps/reclaimation_steps.robot
> +Zed: reclamation table sorting in descending order
Fixed, as suggested

2022-11-24 19:13 UTC, durgesh-verma-spryker commented on resources/steps/reclaimation_steps.robot
> +   [Arguments]    ${sku}    ${reclaim}=1
Fixed

2022-11-24 19:13 UTC, durgesh-verma-spryker commented on resources/steps/reclaimation_steps.robot
> +      ${elementSelector}=    Set Variable    xpath=//table[@data-qa='order-item-list'][${reclaim}]/tbody//td//div[@class='sku'][contains(text(),'${sku}')]/ancestor::tr/td/input[@type="checkbox"]
Fixed

2022-11-24 19:19 UTC, durgesh-verma-spryker commented on resources/steps/reclaimation_steps.robot
> +Zed: check details of latest created reclaimation:
Fixed

2022-11-25 07:05 UTC, durgesh-verma-spryker commented on resources/steps/reclaimation_steps.robot
> +Zed: check state of latest reclaimation:
Fixed

2024-01-18 13:04 UTC, closed without merging