b2b-smoke-OMS-test
spryker/robotframework-suite-tests pull request #375
Opened 2022-10-28 14:49 UTC by durgesh-verma-spryker

## PR Description
https://spryker.atlassian.net/browse/CC-21651
OMS

- Process the order up to Closed state
- Process the order, make some products Refunded
- Process the order, make some products returned then refunded

2022-10-30 17:55 UTC, AntonShopin requested changes

2022-10-30 17:55 UTC, AntonShopin commented on resources/steps/orders_management_steps.robot
> +Zed: trigger all matching states inside this return:
Do we really need this new keyword? 
Looks like we already have `Zed: trigger all matching states inside xxx order: ` and `Zed: trigger all matching states inside this order:`

2022-10-30 17:55 UTC, AntonShopin commented on tests/smoke/smoke_b2b.robot
> +Zed_part_OMS_refund_and_return_then_refund
Please refactor your test. There are 2 ways how to make a refund. The first one is when you create a return -> execute the return and then refund. This case is already covered here https://github.com/spryker/robotframework-suite-tests/blob/master/tests/smoke/smoke_b2b.robot#L564
You need to cover only the second case when we make a refund after the 'delivered' state. 

Also, add in your test assertion, that grand total of the order is reduced on refunded amount. 
Good scenario would be:
* have 2 or more items in the order
* refund only one item from the order -> check that grand total is reduced 
* refund all remaining items using `Zed: trigger all matching states inside this order:` check that grand total is 0 now. 

Please rename your test, don't use 'Zed_part'

2022-10-30 17:55 UTC, AntonShopin commented on tests/smoke/smoke_b2b.robot
> +Zed_part_OMS_order_close
1. Please rename the test. All tests are called like features, don't put `Zed_part_` into the name. A good name would be OMS_close_items
2. Please add [Documetnation] section with the description
3. In your test it would be better to:
* first move to the close state only one of the items -> check that this item is in the closed state and other remain in their states (not closed). With these actions, you'll check that only one item can be 'closed'
* with the next steps move all other items into the closed state using `Zed: trigger all matching states inside this order:`. With these actions, you'll check that all items can be 'closed'
4. At the end check that not the whole order is in the 'closed' state

2022-11-01 15:11 UTC, durgesh-verma-spryker commented on resources/steps/orders_management_steps.robot
> +Zed: trigger all matching states inside this return:
Done as per your suggestions

2022-11-01 15:12 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +Zed_part_OMS_refund_and_return_then_refund
Done based on your suggestions

2022-11-01 15:15 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +Zed_part_OMS_order_close
Done as per your suggestions, but for point 4- I believe you have added "**not** the whole order" by mistakenly Please confirm if I am wrong.

2022-11-16 09:20 UTC, AntonShopin commented on tests/smoke/smoke_b2b.robot
> +    Yves: create new 'Shopping Cart' with name:    complete+${random}
please change the name of the new cart. Each time when you create a cart or create a customer or shopping list or ... ->  try to specify unique names (values). In this case, you create a cart with the name `complete+${random}` in your first and second tests. 

When you run tests in a batch,` ${random}` will be the same. If the first test will fail to due different reasons and the cart won't be deleted, in the second test you'll try to create new cart with exactly the same already existing name. It may cause a failure in your tests.

Long story short. In each test add something unique to you values, which is related to your test. In this example cart can be called: `omsRefund+${random}`

2022-11-16 09:22 UTC, AntonShopin commented on tests/smoke/smoke_b2b.robot
> +Zed_part_OMS_order_close
you are right regarding point #4. I keep this conversation open as one assertion from it is missing (added new comment on it)

2022-11-21 05:52 UTC, durgesh-verma-spryker commented on resources/steps/orders_management_steps.robot
> +Zed: trigger all matching states inside this return:
Removed

2022-11-21 05:53 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +    Yves: create new 'Shopping Cart' with name:    complete+${random}
Fixed

2022-11-21 05:54 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +Zed_part_OMS_order_close
added missing assertion

2022-11-21 05:54 UTC, durgesh-verma-spryker commented on tests/smoke/smoke_b2b.robot
> +    Zed: trigger all matching states inside this order:    Stock update
Fixed

2022-11-22 15:43 UTC, AntonShopin reviewed
The first test "OMS_Close_Items" is ok now, thank you!
The second one is not needed as it fully covered with an already existing one: "Refunds"

You need to extend the second test to cover the following case: 'Process the order, make some products **returned** then refunded'

2024-01-18 13:04 UTC, closed without merging