Feature/frw 1893/master mvp dynamic data exchange api
spryker/robotframework-suite-tests pull request #518
Opened 2023-06-22 11:20 UTC by geega

## PR Description

TBD

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2023-06-22 14:31 UTC, Nataliia-Popkova requested changes

2023-06-22 14:31 UTC, Nataliia-Popkova commented on tests/api/suite/bapi/dynamic_entity/positive.robot
> +    And Response body parameter should be:    [2][id_country]    ${xxc_country_id}
Please add  [Teardown]  section to revert changes.

2023-06-22 14:31 UTC, Nataliia-Popkova commented on tests/api/suite/bapi/dynamic_entity/positive.robot
> +    ### POST GET TOKEN ###
Can be done as a separate keyword and reuse in other tests

2023-06-22 14:31 UTC, Nataliia-Popkova commented on tests/api/suite/bapi/dynamic_entity/positive.robot
> +    And Response body parameter should be:    [0][name]    XXS
Please add [Teardown] section to revert changes.

2023-06-26 07:37 UTC, dimitriyTsemma submitted a review, later dismissed

2023-06-29 11:52 UTC, asmarovydlo requested changes

2023-06-29 11:52 UTC, asmarovydlo commented on tests/api/suite/bapi/dynamic_entity/negative.robot
> +    ### GET WITH INVALID PREFIX ###
```suggestion
    ### GET WITH INVALID RESOURCE NAME ###
```

2023-06-29 11:52 UTC, asmarovydlo commented on tests/api/suite/bapi/dynamic_entity/negative.robot
> +    And Response body parameter should be:    [1][status]    400
How should I understand to which field from the collection the response is related?
Please include the invalid request entity data in the response.

2023-06-29 11:52 UTC, asmarovydlo commented on tests/api/suite/bapi/dynamic_entity/negative.robot
> +    And Response body parameter should be:    [0][status]    500
Should be 404, not 500 error.

2023-06-29 11:52 UTC, asmarovydlo commented on tests/api/suite/bapi/dynamic_entity/negative.robot
> +    And Response body parameter should be:    [0][status]    404
It should be a 500 error (when the configuration is invalid), not a 404.
Here customer did everything right, we have an issue on the server side, and need to fix it.
If it will be 404, we'll never know that we have an issue, if 500 we'll see it in the logs.

2023-06-29 12:27 UTC, geega commented on tests/api/suite/bapi/dynamic_entity/negative.robot
> +    And Response body parameter should be:    [0][status]    404
This case are fixed.

2023-06-29 18:58 UTC, geega commented on tests/api/suite/bapi/dynamic_entity/positive.robot
> +    ### POST GET TOKEN ###
I need help with separate method for this case.

2023-06-29 19:09 UTC, geega commented on tests/api/suite/bapi/dynamic_entity/negative.robot
> +    And Response body parameter should be:    [0][status]    404
This test case removed because we don't have method for handling exception with html stack trace.

2023-06-30 11:26 UTC, asmarovydlo requested changes

2023-06-30 11:26 UTC, asmarovydlo commented on tests/api/suite/bapi/example_endpoints/example/positive.robot
> +#     And Response should return error message:    Not found
Please uncomment

2023-06-30 11:26 UTC, asmarovydlo commented on tests/api/suite/bapi/dynamic_entity/negative.robot
> +    ### GET WITH INVALID RESOURCE NAME ###
```suggestion
    ### GET WITH INVALID PREFIX ###
```

Only this one should be changed

2023-06-30 11:26 UTC, asmarovydlo commented on tests/api/suite/bapi/dynamic_entity/negative.robot
> +    And Response body parameter should contain:    [0][message]    Invalid data value for field: iso2_code. Field rules: max_length: 2, min_length: 2, is_required: 1
https://github.com/spryker/robotframework-suite-tests/pull/518#discussion_r1246506579 not fixed.

2023-06-30 11:30 UTC, dimitriyTsemma commented on tests/api/suite/bapi/example_endpoints/example/positive.robot
> +#     And Response should return error message:    Not found
discussed with @Nataliia-Popkova, and this is a request from her.

2023-06-30 11:53 UTC, geega commented on tests/api/suite/bapi/dynamic_entity/negative.robot
> +    And Response body parameter should contain:    [0][message]    Invalid data value for field: iso2_code. Field rules: max_length: 2, min_length: 2, is_required: 1
So for example we must update error validation message like this: 
```
 Invalid data value for field: iso2_code, entity number: 5. Field rules: max_length: 2, min_length: 2, is_required: 1
```

2023-06-30 12:30 UTC, asmarovydlo commented on tests/api/suite/bapi/example_endpoints/example/positive.robot
> +#     And Response should return error message:    Not found
@Nataliia-Popkova are you fine with it? Would not be better to remove it completely (product absreact are not part of BAPI yet, and not going to be in the neares future)?

2023-06-30 14:37 UTC, asmarovydlo approved these changes

2023-06-30 15:02 UTC, Nataliia-Popkova approved these changes

2023-07-04 09:54 UTC, asmarovydlo approved these changes

2023-07-04 10:22 UTC, yaroslav-spryker approved these changes

2023-07-13 16:43 UTC, Nataliia-Popkova requested changes

2023-07-14 13:06 UTC, Nataliia-Popkova requested changes

2023-07-14 13:06 UTC, Nataliia-Popkova commented on tests/api/suite/bapi/dynamic_entity/negative.robot
> +    And Response body parameter should be:    [1][status]    400
Looks like [Teardown] section missed.

2023-07-14 13:06 UTC, Nataliia-Popkova commented on tests/api/suite/bapi/dynamic_entity/negative.robot
> +    And Response body parameter should be:    [0][status]    400
Looks like [Teardown] section missed.

2023-07-14 13:06 UTC, Nataliia-Popkova commented on tests/api/suite/bapi/dynamic_entity/negative.robot
> +    And Response body parameter should contain:    [0][status]   404
Looks like [Teardown] section missed.

2023-07-14 13:06 UTC, Nataliia-Popkova commented on tests/api/suite/bapi/dynamic_entity/negative.robot
> +    And Response body parameter should be:    [0][code]    501
Looks like [Teardown] section missed.

2023-07-14 13:06 UTC, Nataliia-Popkova commented on tests/api/suite/bapi/dynamic_entity/negative.robot
> +    And Response body parameter should be:    [0][code]    501
Looks like [Teardown] section missed.

2023-07-14 13:06 UTC, Nataliia-Popkova commented on tests/api/suite/bapi/dynamic_entity/negative.robot
> +    And Response body parameter should be:    [0][code]    501
Looks like [Teardown] section missed.

2023-07-14 13:06 UTC, Nataliia-Popkova commented on tests/api/suite/bapi/dynamic_entity/negative.robot
> +    And Response body parameter should be:    [0][code]    007
Looks like [Teardown] section missed.

2023-07-14 13:06 UTC, Nataliia-Popkova commented on tests/api/suite/bapi/dynamic_entity/negative.robot
> +    And Response body parameter should be:    [0][code]    007
Looks like [Teardown] section missed.

2023-07-14 13:06 UTC, Nataliia-Popkova commented on tests/api/suite/bapi/dynamic_entity/negative.robot
> +    And Response should return error message:    Invalid access token.
Looks like [Teardown] section missed.

2023-07-14 13:41 UTC, Nataliia-Popkova approved these changes

2023-07-14 13:47 UTC, Nataliia-Popkova approved these changes

2023-07-14 13:52 UTC, merged