FRW-2435 Adjusted tests for Dynamic Exchange API
spryker/robotframework-suite-tests pull request #577
Opened 2023-08-18 08:55 UTC by olhalivitchuk

## PR Description

https://spryker.atlassian.net/browse/FRW-2435

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2023-08-18 08:57 UTC, dimitriyTsemma submitted a review, later dismissed

2023-08-18 09:10 UTC, asmarovydlo requested changes

2023-08-18 09:10 UTC, asmarovydlo commented on tests/api/suite/bapi/dynamic_entity/positive.robot
> -    And Response body parameter should be:    [0][postal_code_regex]    \\\\d{5}
For `GET /dynamic-entity/product/1` it is fine to have a singular response.
But, `GET /dynamic-entity/products` should return collection, no matter what.

2023-08-18 14:20 UTC, asmarovydlo approved these changes

2023-08-18 14:21 UTC, asmarovydlo approved these changes

2023-08-28 13:06 UTC, Nataliia-Popkova approved these changes

2023-08-28 13:08 UTC, merged