CC-31600: Fixed warehouse user assignment validation
spryker/robotframework-suite-tests pull request #694
Opened 2023-11-14 08:10 UTC by michbeck

#### Overview

- Ticket: https://spryker.atlassian.net/browse/CC-31600
- Release Group: https://release.spryker.com/release-groups/view/5083

###### Optional

Reference all core PRs for auto-link back-references.

Core PRs
- https://github.com/spryker/suite-nonsplit/pull/8351
- https://github.com/spryker/spryker/pull/10580

2023-11-14 11:00 UTC, Nataliia-Popkova commented on tests/api/mp_b2c/bapi/warehouse_user_assignments/positive.robot
> +    [Setup]    Run Keywords    I get access token by user credentials:    ${zed_user.email}
variable issue

2023-11-14 11:00 UTC, Nataliia-Popkova commented on tests/api/mp_b2c/bapi/warehouse_user_assignments/positive.robot
> +    [Setup]    Run Keywords    I get access token by user credentials:    ${zed_user.email}
variable issue

2023-11-14 11:00 UTC, Nataliia-Popkova commented on tests/api/mp_b2c/bapi/warehouse_user_assignments/positive.robot
> +    ...    AND    I set Headers:    Content-Type=${default_header_content_type}    Authorization=Bearer ${token}
variable issue

2023-11-14 11:00 UTC, Nataliia-Popkova commented on tests/api/mp_b2c/bapi/warehouse_user_assignments/positive.robot
> +    ...    AND    I set Headers:    Content-Type=${default_header_content_type}    Authorization=Bearer ${token}
variable issue

2023-11-14 11:00 UTC, Nataliia-Popkova commented on tests/api/mp_b2c/bapi/warehouse_user_assignments/positive.robot
> +    ...    AND    I set Headers:    Content-Type=${default_header_content_type}    Authorization=Bearer ${token}
variable issue

2023-11-14 11:02 UTC, Nataliia-Popkova commented on tests/api/mp_b2c/bapi/warehouse_user_assignments/positive.robot
> +    ...    AND    I set Headers:    Content-Type=${default_header_content_type}    Authorization=Bearer ${token}
variable issue

2023-11-14 11:03 UTC, Nataliia-Popkova commented on tests/api/mp_b2c/bapi/warehouse_user_assignments/positive.robot
> +    ...    AND    I set Headers:    Content-Type=${default_header_content_type}    Authorization=Bearer ${token}
variable issue

2023-11-14 11:08 UTC, Nataliia-Popkova commented on tests/api/b2c/bapi/warehouse_user_assignments/negative.robot
> +    And Make user a warehouse user/ not a warehouse user:   ${warehouse_user_assigment.user_uuid}    1
where do you get this variable? please use the environment file from the b2c demo shop API tests

2023-11-14 11:08 UTC, Nataliia-Popkova commented on tests/api/b2c/bapi/warehouse_user_assignments/negative.robot
> +    And Remove_warehous_user_assigment:    ${warehouse.warehouse_uuid}    ${warehouse_user_assigment.user_uuid}
var issue

2023-11-14 11:08 UTC, Nataliia-Popkova commented on tests/api/b2c/bapi/warehouse_user_assignments/negative.robot
> +    And Create_warehouse_user_assigment:    ${warehouse.warehouse_uuid}    ${warehouse.fk_warehouse_spryker}    ${warehouse_user_assigment.user_uuid}    false
var issue

2023-11-14 11:09 UTC, Nataliia-Popkova commented on tests/api/b2c/bapi/warehouse_user_assignments/negative.robot
> +    And Remove_warehous_user_assigment:    ${warehouse.warehouse_uuid}    ${warehouse_user_assigment.user_uuid}
var issue

2023-11-14 11:09 UTC, Nataliia-Popkova commented on tests/api/b2c/bapi/warehouse_user_assignments/positive.robot
> +    ...    AND    I set Headers:    Content-Type=${default_header_content_type}    Authorization=Bearer ${token}
var issue

2023-11-14 11:09 UTC, Nataliia-Popkova commented on tests/api/b2c/bapi/warehouse_user_assignments/positive.robot
> +    When I send a POST request:    /warehouse-user-assignments    {"data": {"type": "warehouse-user-assignments", "attributes":{"userUuid": "${warehouse_user_assigment.user_uuid}","warehouse" :{"uuid
var issue

2023-11-14 11:09 UTC, Nataliia-Popkova commented on tests/api/b2c/bapi/warehouse_user_assignments/positive.robot
> +    And Response body parameter should be:    [data][attributes][warehouse][name]    ${warehouse.warehouse_name}
var issue

2023-11-14 11:09 UTC, Nataliia-Popkova commented on tests/api/b2c/bapi/warehouse_user_assignments/positive.robot
> +    When I send a POST request:    /warehouse-user-assignments?include=users    {"data": {"type": "warehouse-user-assignments", "attributes":{"userUuid": "${warehouse_user_assigment.user_uuid}","ware
var issue

2023-11-14 11:10 UTC, Nataliia-Popkova commented on tests/api/b2c/bapi/warehouse_user_assignments/positive.robot
> +    And Response body parameter should be:    [included][0][attributes][firstName]    ${warehouse_user_assigment.user_first_name}
var issue

2023-11-14 11:21 UTC, Nataliia-Popkova commented on tests/api/b2c/bapi/warehouse_user_assignments/positive.robot
> +    ...    AND    I set Headers:    Content-Type=${default_header_content_type}    Authorization=Bearer ${token}
var issue

2023-11-14 11:21 UTC, Nataliia-Popkova commented on tests/api/b2c/bapi/warehouse_user_assignments/positive.robot
> +    When I send a POST request:    /warehouse-user-assignments?include=users    {"data": {"type": "warehouse-user-assignments", "attributes":{"userUuid": "${warehouse_user_assigment.user_uuid}","ware
var issue

2023-11-14 11:21 UTC, Nataliia-Popkova commented on tests/api/b2c/bapi/warehouse_user_assignments/positive.robot
> +    And Response body parameter should be:    [data][attributes][warehouse][name]    ${warehouse.warehouse_name}
var issue

2023-11-14 11:22 UTC, Nataliia-Popkova commented on tests/api/b2c/bapi/warehouse_user_assignments/positive.robot
> +    [Setup]    Run Keywords    I get access token by user credentials:    ${zed_user.email}
var issue

2023-11-14 11:22 UTC, Nataliia-Popkova commented on tests/api/b2c/bapi/warehouse_user_assignments/positive.robot
> +    When I send a POST request:    /warehouse-user-assignments?include=users    {"data": {"type": "warehouse-user-assignments", "attributes":{"userUuid": "${warehouse_user_assigment.user_uuid}","ware
var issue

2023-11-14 11:23 UTC, Nataliia-Popkova commented on tests/api/b2c/bapi/warehouse_user_assignments/positive.robot
> +    And Response body parameter should be:    [data][1][attributes][userUuid]    ${warehouse_user_assigment.user_uuid}
var issue

2023-11-14 11:23 UTC, Nataliia-Popkova commented on tests/api/b2c/bapi/warehouse_user_assignments/positive.robot
> +    And Response body parameter should be in:    [data][1][attributes][warehouse][name]    ${warehouse.warehouse_name}    ${warehouse.video_king_warehouse_name}
var issue

2023-11-14 11:23 UTC, Nataliia-Popkova commented on tests/api/b2c/bapi/warehouse_user_assignments/positive.robot
> +    [Setup]    Run Keywords    I get access token by user credentials:    ${zed_user.email}
var issue

2023-11-14 11:23 UTC, Nataliia-Popkova commented on tests/api/b2c/bapi/warehouse_user_assignments/positive.robot
> +    When I send a POST request:    /warehouse-user-assignments?include=users    {"data": {"type": "warehouse-user-assignments", "attributes":{"userUuid": "${warehouse_user_assigment.user_uuid}","ware
var issue

2023-11-14 11:23 UTC, Nataliia-Popkova commented on tests/api/b2c/bapi/warehouse_user_assignments/positive.robot
> +    When I send a POST request:    /warehouse-user-assignments?include=users    {"data": {"type": "warehouse-user-assignments", "attributes":{"userUuid": "${warehouse_user_assigment.user_uuid_2}","wa
var issue

2023-11-14 11:23 UTC, Nataliia-Popkova commented on tests/api/b2c/bapi/warehouse_user_assignments/positive.robot
> +    And Response body parameter should be:    [data][0][attributes][userUuid]    ${warehouse_user_assigment.user_uuid}
var issue

2023-11-14 11:23 UTC, Nataliia-Popkova commented on tests/api/b2c/bapi/warehouse_user_assignments/positive.robot
> +    And Response body parameter should be:    [data][0][attributes][warehouse][uuid]    ${warehouse.warehouse_uuid}
var issue

2023-11-14 11:23 UTC, Nataliia-Popkova commented on tests/api/b2c/bapi/warehouse_user_assignments/positive.robot
> +    ...    AND    Make user a warehouse user/ not a warehouse user:   ${warehouse_user_assigment.user_uuid_2}    1
var issue

2023-11-14 11:24 UTC, Nataliia-Popkova commented on tests/api/b2c/bapi/warehouse_user_assignments/positive.robot
> +    When I send a POST request:    /warehouse-user-assignments?include=users    {"data": {"type": "warehouse-user-assignments", "attributes":{"userUuid": "${warehouse_user_assigment.user_uuid_2}","wa
var issue

2023-11-14 11:24 UTC, Nataliia-Popkova commented on tests/api/b2c/bapi/warehouse_user_assignments/positive.robot
> +    And Response body parameter should be:    [data][0][attributes][warehouse][uuid]    ${warehouse.video_king_warehouse_uuid}
var issue

2023-11-14 11:24 UTC, Nataliia-Popkova commented on tests/api/b2c/bapi/warehouse_user_assignments/positive.robot
> +    ...    AND    Make user a warehouse user/ not a warehouse user:   ${warehouse_user_assigment.user_uuid}    1
var issue

2023-11-14 11:25 UTC, Nataliia-Popkova commented on tests/api/b2c/bapi/warehouse_user_assignments/positive.robot
> +    When I send a POST request:    /warehouse-user-assignments?include=users    {"data": {"type": "warehouse-user-assignments", "attributes":{"userUuid": "${warehouse_user_assigment.user_uuid}","ware
verify all changes. varaibles should be from api_b2c env file

2023-11-14 14:57 UTC, Nataliia-Popkova approved these changes

2023-11-16 07:54 UTC, Nataliia-Popkova requested changes

2023-11-16 07:54 UTC, Nataliia-Popkova commented on tests/api/b2c/bapi/warehouse_user_assignments/negative.robot
> +    And Make user a warehouse user/ not a warehouse user:   ${admin_user_uuid}    0
Please add a Teardown section for requests where you revert data.
Please keep correct spacing: 4 spacing should be after the keyword before properties:
And Make user a warehouse user/ not a warehouse user:    ${admin_user_uuid}    0

This is a general comment, please fix teardown sections and keep correct spacings

2023-11-16 13:16 UTC, michbeck commented on tests/api/b2c/bapi/warehouse_user_assignments/negative.robot
> +    And Make user a warehouse user/ not a warehouse user:   ${admin_user_uuid}    0
The following was done as requested:
- Spacing adjusted to have 4 spaces
- Setup & Teardown section added

2023-11-16 13:53 UTC, Nataliia-Popkova approved these changes

2023-11-16 13:57 UTC, merged