FRW-6430: Covered POST and PATCH methods for complex endpoints with tests
spryker/robotframework-suite-tests pull request #768
Opened 2024-01-08 21:05 UTC by olhalivitchuk

## PR Description
 
https://spryker.atlassian.net/browse/FRW-6430

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2024-01-09 10:16 UTC, dimitriyTsemma commented on tests/api/suite/bapi/dynamic_entity/complex/positive.robot
> +    And I send a POST request:    /dynamic-entity/robot-tests-product-abstracts  {"data": [{"fk_tax_set": 1, "attributes": "FOO", "sku": "FOO", "robotTestsConcreteProducts": [{"attributes": "FOOBAR",
Please create one more test with multiple relations (for example abstract-product with relations for the concrete product, product category, and category ).
because in doc generation we faced issues with multiple relations

2024-01-15 15:32 UTC, olhalivitchuk commented on tests/api/suite/bapi/dynamic_entity/complex/positive.robot
> +    And I send a POST request:    /dynamic-entity/robot-tests-product-abstracts  {"data": [{"fk_tax_set": 1, "attributes": "FOO", "sku": "FOO", "robotTestsConcreteProducts": [{"attributes": "FOOBAR",
Discussed.

2024-01-15 21:26 UTC, dimitriyTsemma requested changes

2024-01-15 21:26 UTC, dimitriyTsemma commented on tests/api/suite/bapi/dynamic_entity/complex/negative.robot
> +    Delete dynamic entity configuration relation in Database:    roboTestsCategories
```suggestion
    Delete dynamic entity configuration relation in Database:    robotTestsCategories
```

please fix all other place

2024-01-15 21:26 UTC, dimitriyTsemma commented on tests/api/suite/bapi/dynamic_entity/complex/negative.robot
> +    Delete dynamic entity configuration relation in Database:    roboTestsProductCategories
```suggestion
    Delete dynamic entity configuration relation in Database:    robotTestsProductCategories
```
please fix all other place

2024-01-15 21:26 UTC, dimitriyTsemma commented on tests/api/suite/bapi/dynamic_entity/complex/negative.robot
> +    Delete dynamic entity configuration relation in Database:    roboTestsConcreteProducts
```suggestion
    Delete dynamic entity configuration relation in Database:    robotTestsConcreteProducts
```
please fix all other places

2024-01-15 21:26 UTC, dimitriyTsemma commented on tests/api/suite/bapi/dynamic_entity/complex/negative.robot
> +    Delete dynamic entity configuration in Database:    robotests-product-abstracts
```suggestion
    Delete dynamic entity configuration in Database:    robot-tests-product-abstracts
```
please fix all other places with the same rules

2024-01-15 21:26 UTC, dimitriyTsemma commented on tests/api/suite/bapi/dynamic_entity/complex/positive.robot
> +#    Delete dynamic entity configuration in Database:    robotests-categories
why commented?

2024-01-16 08:25 UTC, geega approved these changes

2024-01-16 09:12 UTC, yaroslav-spryker approved these changes

2024-01-16 10:40 UTC, dimitriyTsemma approved these changes

2024-01-17 09:22 UTC, asmarovydlo approved these changes

2024-01-17 09:22 UTC, asmarovydlo commented on tests/api/suite/bapi/dynamic_entity/complex/positive.robot
> +    And I send a GET request:    /dynamic-entity/robot-tests-product-abstracts?include=robotTestsProductAbstractProducts.robotTestsProductCategories.robotTestsCategories
If we'll have related bugs, I would recommend switching to not existing table configuration, instead of using products and categories.

2024-01-26 08:17 UTC, limeeugenia submitted a review, later dismissed

2024-01-26 09:02 UTC, dimitriyTsemma approved these changes

2024-01-29 14:47 UTC, merged