FRW-6879 Test coverage
spryker/robotframework-suite-tests pull request #835
Opened 2024-02-29 15:22 UTC by dimitriyTsemma

## PR Description

https://spryker.atlassian.net/browse/FRW-7315

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2024-03-01 11:51 UTC, olhalivitchuk submitted a review, later dismissed

2024-03-06 10:52 UTC, asmarovydlo requested changes

2024-03-06 10:52 UTC, asmarovydlo commented on tests/api/suite/bapi/dynamic_entity/negative.robot
> +    Then Response status code should be:    200
Why the response is 200, if test name is `Get_country_collection_with_invalid_multiple_filter`?

2024-03-06 12:20 UTC, asmarovydlo approved these changes

2024-03-07 16:43 UTC, merged