FRW-8883 Fixed customer login so that email confirmation is checked and errors are correctly reported.
spryker/robotframework-suite-tests pull request #960
Opened 2024-10-04 23:53 UTC by aleksandr-velikanov

Ticket:  https://spryker.atlassian.net/browse/FRW-8883

- Added a test for customer login with an unconfirmed email
- Added a keyword to log in a customer into Yves and expect an error

2024-10-07 08:04 UTC, AntonShopin reviewed
Please create the same test for demoshops (b2b, b2c, b2b-mp, b2c-mp) as well

2024-10-07 08:04 UTC, AntonShopin commented on tests/ui/suite/customers/customer.robot
> +    ...    || Mr.        | New        | User      | sonia+${random}@spryker.com  | Ps${random_str_password}!5${random_id_password} ||
Please change the email address that you use in the test. The problem is that there is another test that creates a new customer with `sonia+${random}@spryker.com`, so in this test most probably registration will fail as the email address is already in use. 

Change it on smth unique, like `sonia+fail${random}@spryker.com`

2024-10-09 11:33 UTC, kraal-spryker approved these changes

2024-10-10 07:29 UTC, AntonShopin approved these changes

2024-10-14 14:31 UTC, asmarovydlo requested changes

2024-10-14 14:31 UTC, asmarovydlo commented on tests/ui/mp_b2c/customers/customer.robot
> +    [Documentation]    Check that a new user can cannot login if the email is not verified
So, can or can't?

2024-10-14 14:31 UTC, asmarovydlo commented on tests/ui/b2c/customers/customer.robot
> +    [Documentation]    Check that a new user can cannot login if the email is not verified
So, can or can't?

2024-10-14 14:31 UTC, asmarovydlo commented on tests/ui/suite/customers/customer.robot
> +    [Documentation]    Check that a new user can cannot login if the email is not verified
So, can or can't?

2024-10-16 13:45 UTC, asmarovydlo approved these changes

2024-10-16 13:46 UTC, merged